package OPERATIONPROJECT.model.BC.EO;

import java.math.BigDecimal;

import java.sql.Time;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 23 10:19:39 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CarReconciliationEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        DriverName,
        ReturnDate,
        ShipmentId,
        CoverDate,
        ToCoverDate,
        StatusName,
        DataStatus,
        DataAgent,
        OperationAgent,
        ToCoverDate1,
        ShipmentDate,
        CoverDate1,
        Shipment,
        RelatedShipment,
        ContractsReview,
        ReconciliationNotes,
        CarReconHubRecon,
        CarReconPilotsLostNew,
        PilotReconciliationSummary,
        CarReconCarSummary;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DRIVERNAME = AttributesEnum.DriverName.index();
    public static final int RETURNDATE = AttributesEnum.ReturnDate.index();
    public static final int SHIPMENTID = AttributesEnum.ShipmentId.index();
    public static final int COVERDATE = AttributesEnum.CoverDate.index();
    public static final int TOCOVERDATE = AttributesEnum.ToCoverDate.index();
    public static final int STATUSNAME = AttributesEnum.StatusName.index();
    public static final int DATASTATUS = AttributesEnum.DataStatus.index();
    public static final int DATAAGENT = AttributesEnum.DataAgent.index();
    public static final int OPERATIONAGENT = AttributesEnum.OperationAgent.index();
    public static final int TOCOVERDATE1 = AttributesEnum.ToCoverDate1.index();
    public static final int SHIPMENTDATE = AttributesEnum.ShipmentDate.index();
    public static final int COVERDATE1 = AttributesEnum.CoverDate1.index();
    public static final int SHIPMENT = AttributesEnum.Shipment.index();
    public static final int RELATEDSHIPMENT = AttributesEnum.RelatedShipment.index();
    public static final int CONTRACTSREVIEW = AttributesEnum.ContractsReview.index();
    public static final int RECONCILIATIONNOTES = AttributesEnum.ReconciliationNotes.index();
    public static final int CARRECONHUBRECON = AttributesEnum.CarReconHubRecon.index();
    public static final int CARRECONPILOTSLOSTNEW = AttributesEnum.CarReconPilotsLostNew.index();
    public static final int PILOTRECONCILIATIONSUMMARY = AttributesEnum.PilotReconciliationSummary.index();
    public static final int CARRECONCARSUMMARY = AttributesEnum.CarReconCarSummary.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CarReconciliationEOImpl() {
    }

    /**
     * @param shipmentId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal shipmentId) {
        return new Key(new Object[] { shipmentId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("OPERATIONPROJECT.model.BC.EO.CarReconciliationEO");
    }


}

