package OPERATIONPROJECT.model.BC.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 27 21:06:04 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductLostRlostEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        ShipmentId,
        LostDate,
        ProductId,
        LostQuantity,
        Status,
        QtyReturned,
        ReturnDate,
        PilotId,
        ReturnAgent,
        LostAgent,
        Type;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int SHIPMENTID = AttributesEnum.ShipmentId.index();
    public static final int LOSTDATE = AttributesEnum.LostDate.index();
    public static final int PRODUCTID = AttributesEnum.ProductId.index();
    public static final int LOSTQUANTITY = AttributesEnum.LostQuantity.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int QTYRETURNED = AttributesEnum.QtyReturned.index();
    public static final int RETURNDATE = AttributesEnum.ReturnDate.index();
    public static final int PILOTID = AttributesEnum.PilotId.index();
    public static final int RETURNAGENT = AttributesEnum.ReturnAgent.index();
    public static final int LOSTAGENT = AttributesEnum.LostAgent.index();
    public static final int TYPE = AttributesEnum.Type.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProductLostRlostEOImpl() {
    }

    @Override
    protected void doDML(int i, TransactionEvent transactionEvent) {
        // TODO Implement this method
        super.doDML(i, transactionEvent);
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public BigDecimal getId() {
        return (BigDecimal) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(BigDecimal value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for ShipmentId, using the alias name ShipmentId.
     * @return the value of ShipmentId
     */
    public BigDecimal getShipmentId() {
        return (BigDecimal) getAttributeInternal(SHIPMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipmentId.
     * @param value value to set the ShipmentId
     */
    public void setShipmentId(BigDecimal value) {
        setAttributeInternal(SHIPMENTID, value);
    }

    /**
     * Gets the attribute value for LostDate, using the alias name LostDate.
     * @return the value of LostDate
     */
    public Timestamp getLostDate() {
        return (Timestamp) getAttributeInternal(LOSTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LostDate.
     * @param value value to set the LostDate
     */
    public void setLostDate(Timestamp value) {
        setAttributeInternal(LOSTDATE, value);
    }

    /**
     * Gets the attribute value for ProductId, using the alias name ProductId.
     * @return the value of ProductId
     */
    public String getProductId() {
        return (String) getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductId.
     * @param value value to set the ProductId
     */
    public void setProductId(String value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for LostQuantity, using the alias name LostQuantity.
     * @return the value of LostQuantity
     */
    public BigDecimal getLostQuantity() {
        return (BigDecimal) getAttributeInternal(LOSTQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LostQuantity.
     * @param value value to set the LostQuantity
     */
    public void setLostQuantity(BigDecimal value) {
        setAttributeInternal(LOSTQUANTITY, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public BigDecimal getStatus() {
        return (BigDecimal) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(BigDecimal value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for QtyReturned, using the alias name QtyReturned.
     * @return the value of QtyReturned
     */
    public BigDecimal getQtyReturned() {
        return (BigDecimal) getAttributeInternal(QTYRETURNED);
    }

    /**
     * Sets <code>value</code> as the attribute value for QtyReturned.
     * @param value value to set the QtyReturned
     */
    public void setQtyReturned(BigDecimal value) {
        setAttributeInternal(QTYRETURNED, value);
    }

    /**
     * Gets the attribute value for ReturnDate, using the alias name ReturnDate.
     * @return the value of ReturnDate
     */
    public Timestamp getReturnDate() {
        return (Timestamp) getAttributeInternal(RETURNDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReturnDate.
     * @param value value to set the ReturnDate
     */
    public void setReturnDate(Timestamp value) {
        setAttributeInternal(RETURNDATE, value);
    }

    /**
     * Gets the attribute value for PilotId, using the alias name PilotId.
     * @return the value of PilotId
     */
    public String getPilotId() {
        return (String) getAttributeInternal(PILOTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PilotId.
     * @param value value to set the PilotId
     */
    public void setPilotId(String value) {
        setAttributeInternal(PILOTID, value);
    }

    /**
     * Gets the attribute value for ReturnAgent, using the alias name ReturnAgent.
     * @return the value of ReturnAgent
     */
    public String getReturnAgent() {
        return (String) getAttributeInternal(RETURNAGENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReturnAgent.
     * @param value value to set the ReturnAgent
     */
    public void setReturnAgent(String value) {
        setAttributeInternal(RETURNAGENT, value);
    }

    /**
     * Gets the attribute value for LostAgent, using the alias name LostAgent.
     * @return the value of LostAgent
     */
    public String getLostAgent() {
        return (String) getAttributeInternal(LOSTAGENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for LostAgent.
     * @param value value to set the LostAgent
     */
    public void setLostAgent(String value) {
        setAttributeInternal(LOSTAGENT, value);
    }

    /**
     * Gets the attribute value for Type, using the alias name Type.
     * @return the value of Type
     */
    public BigDecimal getType() {
        return (BigDecimal) getAttributeInternal(TYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Type.
     * @param value value to set the Type
     */
    public void setType(BigDecimal value) {
        setAttributeInternal(TYPE, value);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal id) {
        return new Key(new Object[] { id });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("OPERATIONPROJECT.model.BC.EO.ProductLostRlostEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }
}

