package OPERATIONPROJECT.model.BC.EO;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 28 15:52:36 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Shipment1EOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ShipmentId,
        DriverId,
        ShipmentType,
        Status,
        PayableStatus,
        CoverDate,
        ShipmentDate,
        Locked,
        Paid,
        FacilityId,
        CreatedBy,
        RelatedShipments,
        InsertTime,
        DataStatus,
        EditIn,
        EditInAttachment,
        EditOutAttachment,
        EditedBy,
        EditDate,
        EditOut,
        Comment,
        PilotCoverComment,
        PilotCoverEditTime,
        PilotCoverEditedBy,
        PilotCoverEdited,
        Verified,
        ClosedBy,
        CloseTime,
        OperationAgent,
        DataAgent,
        Edited,
        DispatchedBy,
        ShipemntStatus,
        UpdatedBy,
        CarIssue;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    @Override
    protected void doDML(int i, TransactionEvent transactionEvent) {
        // TODO Implement this method
        if(i==DML_UPDATE){
            setEditedBy(ADFContext.getCurrent().getSecurityContext().getUserName());
            setEdited(new BigDecimal("1"));
            setEditDate(new Timestamp(System.currentTimeMillis()));
        }
        super.doDML(i, transactionEvent);
    }


    public static final int SHIPMENTID = AttributesEnum.ShipmentId.index();
    public static final int DRIVERID = AttributesEnum.DriverId.index();
    public static final int SHIPMENTTYPE = AttributesEnum.ShipmentType.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int PAYABLESTATUS = AttributesEnum.PayableStatus.index();
    public static final int COVERDATE = AttributesEnum.CoverDate.index();
    public static final int SHIPMENTDATE = AttributesEnum.ShipmentDate.index();
    public static final int LOCKED = AttributesEnum.Locked.index();
    public static final int PAID = AttributesEnum.Paid.index();
    public static final int FACILITYID = AttributesEnum.FacilityId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int RELATEDSHIPMENTS = AttributesEnum.RelatedShipments.index();
    public static final int INSERTTIME = AttributesEnum.InsertTime.index();
    public static final int DATASTATUS = AttributesEnum.DataStatus.index();
    public static final int EDITIN = AttributesEnum.EditIn.index();
    public static final int EDITINATTACHMENT = AttributesEnum.EditInAttachment.index();
    public static final int EDITOUTATTACHMENT = AttributesEnum.EditOutAttachment.index();
    public static final int EDITEDBY = AttributesEnum.EditedBy.index();
    public static final int EDITDATE = AttributesEnum.EditDate.index();
    public static final int EDITOUT = AttributesEnum.EditOut.index();
    public static final int COMMENT = AttributesEnum.Comment.index();
    public static final int PILOTCOVERCOMMENT = AttributesEnum.PilotCoverComment.index();
    public static final int PILOTCOVEREDITTIME = AttributesEnum.PilotCoverEditTime.index();
    public static final int PILOTCOVEREDITEDBY = AttributesEnum.PilotCoverEditedBy.index();
    public static final int PILOTCOVEREDITED = AttributesEnum.PilotCoverEdited.index();
    public static final int VERIFIED = AttributesEnum.Verified.index();
    public static final int CLOSEDBY = AttributesEnum.ClosedBy.index();
    public static final int CLOSETIME = AttributesEnum.CloseTime.index();
    public static final int OPERATIONAGENT = AttributesEnum.OperationAgent.index();
    public static final int DATAAGENT = AttributesEnum.DataAgent.index();
    public static final int EDITED = AttributesEnum.Edited.index();
    public static final int DISPATCHEDBY = AttributesEnum.DispatchedBy.index();
    public static final int SHIPEMNTSTATUS = AttributesEnum.ShipemntStatus.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int CARISSUE = AttributesEnum.CarIssue.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Shipment1EOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("OPERATIONPROJECT.model.BC.EO.Shipment1EO");
    }


    /**
     * Gets the attribute value for ShipmentId, using the alias name ShipmentId.
     * @return the value of ShipmentId
     */
    public BigInteger getShipmentId() {
        return (BigInteger) getAttributeInternal(SHIPMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipmentId.
     * @param value value to set the ShipmentId
     */
    public void setShipmentId(BigInteger value) {
        setAttributeInternal(SHIPMENTID, value);
    }

    /**
     * Gets the attribute value for DriverId, using the alias name DriverId.
     * @return the value of DriverId
     */
    public String getDriverId() {
        return (String) getAttributeInternal(DRIVERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DriverId.
     * @param value value to set the DriverId
     */
    public void setDriverId(String value) {
        setAttributeInternal(DRIVERID, value);
    }

    /**
     * Gets the attribute value for ShipmentType, using the alias name ShipmentType.
     * @return the value of ShipmentType
     */
    public BigDecimal getShipmentType() {
        return (BigDecimal) getAttributeInternal(SHIPMENTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipmentType.
     * @param value value to set the ShipmentType
     */
    public void setShipmentType(BigDecimal value) {
        setAttributeInternal(SHIPMENTTYPE, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public BigDecimal getStatus() {
        return (BigDecimal) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(BigDecimal value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for PayableStatus, using the alias name PayableStatus.
     * @return the value of PayableStatus
     */
    public BigDecimal getPayableStatus() {
        return (BigDecimal) getAttributeInternal(PAYABLESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for PayableStatus.
     * @param value value to set the PayableStatus
     */
    public void setPayableStatus(BigDecimal value) {
        setAttributeInternal(PAYABLESTATUS, value);
    }

    /**
     * Gets the attribute value for CoverDate, using the alias name CoverDate.
     * @return the value of CoverDate
     */
    public Timestamp getCoverDate() {
        return (Timestamp) getAttributeInternal(COVERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoverDate.
     * @param value value to set the CoverDate
     */
    public void setCoverDate(Timestamp value) {
        setAttributeInternal(COVERDATE, value);
    }

    /**
     * Gets the attribute value for ShipmentDate, using the alias name ShipmentDate.
     * @return the value of ShipmentDate
     */
    public Timestamp getShipmentDate() {
        return (Timestamp) getAttributeInternal(SHIPMENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipmentDate.
     * @param value value to set the ShipmentDate
     */
    public void setShipmentDate(Timestamp value) {
        setAttributeInternal(SHIPMENTDATE, value);
    }

    /**
     * Gets the attribute value for Locked, using the alias name Locked.
     * @return the value of Locked
     */
    public BigDecimal getLocked() {
        return (BigDecimal) getAttributeInternal(LOCKED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Locked.
     * @param value value to set the Locked
     */
    public void setLocked(BigDecimal value) {
        setAttributeInternal(LOCKED, value);
    }

    /**
     * Gets the attribute value for Paid, using the alias name Paid.
     * @return the value of Paid
     */
    public BigDecimal getPaid() {
        return (BigDecimal) getAttributeInternal(PAID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Paid.
     * @param value value to set the Paid
     */
    public void setPaid(BigDecimal value) {
        setAttributeInternal(PAID, value);
    }

    /**
     * Gets the attribute value for FacilityId, using the alias name FacilityId.
     * @return the value of FacilityId
     */
    public BigDecimal getFacilityId() {
        return (BigDecimal) getAttributeInternal(FACILITYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FacilityId.
     * @param value value to set the FacilityId
     */
    public void setFacilityId(BigDecimal value) {
        setAttributeInternal(FACILITYID, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for RelatedShipments, using the alias name RelatedShipments.
     * @return the value of RelatedShipments
     */
    public String getRelatedShipments() {
        return (String) getAttributeInternal(RELATEDSHIPMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for RelatedShipments.
     * @param value value to set the RelatedShipments
     */
    public void setRelatedShipments(String value) {
        setAttributeInternal(RELATEDSHIPMENTS, value);
    }

    /**
     * Gets the attribute value for InsertTime, using the alias name InsertTime.
     * @return the value of InsertTime
     */
    public Timestamp getInsertTime() {
        return (Timestamp) getAttributeInternal(INSERTTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for InsertTime.
     * @param value value to set the InsertTime
     */
    public void setInsertTime(Timestamp value) {
        setAttributeInternal(INSERTTIME, value);
    }

    /**
     * Gets the attribute value for DataStatus, using the alias name DataStatus.
     * @return the value of DataStatus
     */
    public BigDecimal getDataStatus() {
        return (BigDecimal) getAttributeInternal(DATASTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DataStatus.
     * @param value value to set the DataStatus
     */
    public void setDataStatus(BigDecimal value) {
        setAttributeInternal(DATASTATUS, value);
    }

    /**
     * Gets the attribute value for EditIn, using the alias name EditIn.
     * @return the value of EditIn
     */
    public BigDecimal getEditIn() {
        return (BigDecimal) getAttributeInternal(EDITIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for EditIn.
     * @param value value to set the EditIn
     */
    public void setEditIn(BigDecimal value) {
        setAttributeInternal(EDITIN, value);
    }

    /**
     * Gets the attribute value for EditInAttachment, using the alias name EditInAttachment.
     * @return the value of EditInAttachment
     */
    public String getEditInAttachment() {
        return (String) getAttributeInternal(EDITINATTACHMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for EditInAttachment.
     * @param value value to set the EditInAttachment
     */
    public void setEditInAttachment(String value) {
        setAttributeInternal(EDITINATTACHMENT, value);
    }

    /**
     * Gets the attribute value for EditOutAttachment, using the alias name EditOutAttachment.
     * @return the value of EditOutAttachment
     */
    public String getEditOutAttachment() {
        return (String) getAttributeInternal(EDITOUTATTACHMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for EditOutAttachment.
     * @param value value to set the EditOutAttachment
     */
    public void setEditOutAttachment(String value) {
        setAttributeInternal(EDITOUTATTACHMENT, value);
    }

    /**
     * Gets the attribute value for EditedBy, using the alias name EditedBy.
     * @return the value of EditedBy
     */
    public String getEditedBy() {
        return (String) getAttributeInternal(EDITEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for EditedBy.
     * @param value value to set the EditedBy
     */
    public void setEditedBy(String value) {
        setAttributeInternal(EDITEDBY, value);
    }

    /**
     * Gets the attribute value for EditDate, using the alias name EditDate.
     * @return the value of EditDate
     */
    public Timestamp getEditDate() {
        return (Timestamp) getAttributeInternal(EDITDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EditDate.
     * @param value value to set the EditDate
     */
    public void setEditDate(Timestamp value) {
        setAttributeInternal(EDITDATE, value);
    }

    /**
     * Gets the attribute value for EditOut, using the alias name EditOut.
     * @return the value of EditOut
     */
    public BigDecimal getEditOut() {
        return (BigDecimal) getAttributeInternal(EDITOUT);
    }

    /**
     * Sets <code>value</code> as the attribute value for EditOut.
     * @param value value to set the EditOut
     */
    public void setEditOut(BigDecimal value) {
        setAttributeInternal(EDITOUT, value);
    }

    /**
     * Gets the attribute value for Comment, using the alias name Comment.
     * @return the value of Comment
     */
    public String getComment() {
        return (String) getAttributeInternal(COMMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Comment.
     * @param value value to set the Comment
     */
    public void setComment(String value) {
        setAttributeInternal(COMMENT, value);
    }

    /**
     * Gets the attribute value for PilotCoverComment, using the alias name PilotCoverComment.
     * @return the value of PilotCoverComment
     */
    public String getPilotCoverComment() {
        return (String) getAttributeInternal(PILOTCOVERCOMMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for PilotCoverComment.
     * @param value value to set the PilotCoverComment
     */
    public void setPilotCoverComment(String value) {
        setAttributeInternal(PILOTCOVERCOMMENT, value);
    }

    /**
     * Gets the attribute value for PilotCoverEditTime, using the alias name PilotCoverEditTime.
     * @return the value of PilotCoverEditTime
     */
    public Timestamp getPilotCoverEditTime() {
        return (Timestamp) getAttributeInternal(PILOTCOVEREDITTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for PilotCoverEditTime.
     * @param value value to set the PilotCoverEditTime
     */
    public void setPilotCoverEditTime(Timestamp value) {
        setAttributeInternal(PILOTCOVEREDITTIME, value);
    }

    /**
     * Gets the attribute value for PilotCoverEditedBy, using the alias name PilotCoverEditedBy.
     * @return the value of PilotCoverEditedBy
     */
    public String getPilotCoverEditedBy() {
        return (String) getAttributeInternal(PILOTCOVEREDITEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PilotCoverEditedBy.
     * @param value value to set the PilotCoverEditedBy
     */
    public void setPilotCoverEditedBy(String value) {
        setAttributeInternal(PILOTCOVEREDITEDBY, value);
    }

    /**
     * Gets the attribute value for PilotCoverEdited, using the alias name PilotCoverEdited.
     * @return the value of PilotCoverEdited
     */
    public BigDecimal getPilotCoverEdited() {
        return (BigDecimal) getAttributeInternal(PILOTCOVEREDITED);
    }

    /**
     * Sets <code>value</code> as the attribute value for PilotCoverEdited.
     * @param value value to set the PilotCoverEdited
     */
    public void setPilotCoverEdited(BigDecimal value) {
        setAttributeInternal(PILOTCOVEREDITED, value);
    }

    /**
     * Gets the attribute value for Verified, using the alias name Verified.
     * @return the value of Verified
     */
    public BigDecimal getVerified() {
        return (BigDecimal) getAttributeInternal(VERIFIED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Verified.
     * @param value value to set the Verified
     */
    public void setVerified(BigDecimal value) {
        setAttributeInternal(VERIFIED, value);
    }

    /**
     * Gets the attribute value for ClosedBy, using the alias name ClosedBy.
     * @return the value of ClosedBy
     */
    public String getClosedBy() {
        return (String) getAttributeInternal(CLOSEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ClosedBy.
     * @param value value to set the ClosedBy
     */
    public void setClosedBy(String value) {
        setAttributeInternal(CLOSEDBY, value);
    }

    /**
     * Gets the attribute value for CloseTime, using the alias name CloseTime.
     * @return the value of CloseTime
     */
    public Timestamp getCloseTime() {
        return (Timestamp) getAttributeInternal(CLOSETIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CloseTime.
     * @param value value to set the CloseTime
     */
    public void setCloseTime(Timestamp value) {
        setAttributeInternal(CLOSETIME, value);
    }

    /**
     * Gets the attribute value for OperationAgent, using the alias name OperationAgent.
     * @return the value of OperationAgent
     */
    public String getOperationAgent() {
        return (String) getAttributeInternal(OPERATIONAGENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperationAgent.
     * @param value value to set the OperationAgent
     */
    public void setOperationAgent(String value) {
        setAttributeInternal(OPERATIONAGENT, value);
    }

    /**
     * Gets the attribute value for DataAgent, using the alias name DataAgent.
     * @return the value of DataAgent
     */
    public String getDataAgent() {
        return (String) getAttributeInternal(DATAAGENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DataAgent.
     * @param value value to set the DataAgent
     */
    public void setDataAgent(String value) {
        setAttributeInternal(DATAAGENT, value);
    }

    /**
     * Gets the attribute value for Edited, using the alias name Edited.
     * @return the value of Edited
     */
    public BigDecimal getEdited() {
        return (BigDecimal) getAttributeInternal(EDITED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Edited.
     * @param value value to set the Edited
     */
    public void setEdited(BigDecimal value) {
        setAttributeInternal(EDITED, value);
    }

    /**
     * Gets the attribute value for DispatchedBy, using the alias name DispatchedBy.
     * @return the value of DispatchedBy
     */
    public String getDispatchedBy() {
        return (String) getAttributeInternal(DISPATCHEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for DispatchedBy.
     * @param value value to set the DispatchedBy
     */
    public void setDispatchedBy(String value) {
        setAttributeInternal(DISPATCHEDBY, value);
    }

    /**
     * Gets the attribute value for ShipemntStatus, using the alias name ShipemntStatus.
     * @return the value of ShipemntStatus
     */
    public BigDecimal getShipemntStatus() {
        return (BigDecimal) getAttributeInternal(SHIPEMNTSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipemntStatus.
     * @param value value to set the ShipemntStatus
     */
    public void setShipemntStatus(BigDecimal value) {
        setAttributeInternal(SHIPEMNTSTATUS, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getCarIssue() {
        return (RowIterator) getAttributeInternal(CARISSUE);
    }


    /**
     * @param shipmentId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigInteger shipmentId) {
        return new Key(new Object[] { shipmentId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }
}

