package OPERATIONPROJECT.model.BC.VO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.BFileDomain;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 16 13:03:09 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AssNotesReviewDetailsVORowImpl extends ViewRowImpl {


    public static final int ENTITY_ASSNOTESREVIEWDETAILSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AssignDate,
        AreaId,
        AreaName,
        DataAgent,
        DriverName,
        DrivId,
        PilotName,
        PilotId,
        AssignmentId,
        Status,
        CloseCodeReason,
        CardNo,
        CustomerNotes,
        ClientName,
        Duration,
        ActualPaid,
        DataStatus,
        SelectedId,
        PackSelected,
        VALID,
        CheckPackageName,
        DataTeamAgentNotesReview,
        ProductContract,
        ProductContractDDownload,
        ProductContractView,
        DataStatusActionVO1,
        CloseCodesGroupsVO1,
        CloseCodeReasonsVO1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ASSIGNDATE = AttributesEnum.AssignDate.index();
    public static final int AREAID = AttributesEnum.AreaId.index();
    public static final int AREANAME = AttributesEnum.AreaName.index();
    public static final int DATAAGENT = AttributesEnum.DataAgent.index();
    public static final int DRIVERNAME = AttributesEnum.DriverName.index();
    public static final int DRIVID = AttributesEnum.DrivId.index();
    public static final int PILOTNAME = AttributesEnum.PilotName.index();
    public static final int PILOTID = AttributesEnum.PilotId.index();
    public static final int ASSIGNMENTID = AttributesEnum.AssignmentId.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int CLOSECODEREASON = AttributesEnum.CloseCodeReason.index();
    public static final int CARDNO = AttributesEnum.CardNo.index();
    public static final int CUSTOMERNOTES = AttributesEnum.CustomerNotes.index();
    public static final int CLIENTNAME = AttributesEnum.ClientName.index();
    public static final int DURATION = AttributesEnum.Duration.index();
    public static final int ACTUALPAID = AttributesEnum.ActualPaid.index();
    public static final int DATASTATUS = AttributesEnum.DataStatus.index();
    public static final int SELECTEDID = AttributesEnum.SelectedId.index();
    public static final int PACKSELECTED = AttributesEnum.PackSelected.index();
    public static final int VALID = AttributesEnum.VALID.index();
    public static final int CHECKPACKAGENAME = AttributesEnum.CheckPackageName.index();
    public static final int DATATEAMAGENTNOTESREVIEW = AttributesEnum.DataTeamAgentNotesReview.index();
    public static final int PRODUCTCONTRACT = AttributesEnum.ProductContract.index();
    public static final int PRODUCTCONTRACTDDOWNLOAD = AttributesEnum.ProductContractDDownload.index();
    public static final int PRODUCTCONTRACTVIEW = AttributesEnum.ProductContractView.index();
    public static final int DATASTATUSACTIONVO1 = AttributesEnum.DataStatusActionVO1.index();
    public static final int CLOSECODESGROUPSVO1 = AttributesEnum.CloseCodesGroupsVO1.index();
    public static final int CLOSECODEREASONSVO1 = AttributesEnum.CloseCodeReasonsVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AssNotesReviewDetailsVORowImpl() {
    }
}

