package OPERATIONPROJECT.model.BC.VO;

import java.sql.CallableStatement;

import java.sql.SQLException;

import oracle.adf.share.ADFContext;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 04 01:07:29 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CarReconciliationVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CarReconciliationVOImpl() {
        
        
    }
    public int submit_post(String ids, String agents , String user_name) {
        int var=0;
        CallableStatement cs=null;
        String query="call ASSIGN_OPERATION_AGENT(?,?,?)";
        try{
        cs=getDBTransaction().createCallableStatement(query, getDBTransaction().DEFAULT);
            cs.setString(1, ids);
            cs.setString(2,agents);
            cs.setString(3, user_name);
            var=cs.executeUpdate();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        finally{
            try {
                cs.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        return var;
    }

    /**
     * Returns the bind variable value for P_CURRENT_USER.
     * @return bind variable value for P_CURRENT_USER
     */
    public String getP_CURRENT_USER() {
        return (String) getNamedWhereClauseParam("P_CURRENT_USER");
    }

    /**
     * Sets <code>value</code> for bind variable P_CURRENT_USER.
     * @param value value to bind as P_CURRENT_USER
     */
    public void setP_CURRENT_USER(String value) {
        setNamedWhereClauseParam("P_CURRENT_USER", value);
    }
}

