package OPERATIONPROJECT.model.BC.VO;

import OPERATIONPROJECT.model.BC.EO.CarReconciliationEOImpl;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.Time;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 05 12:43:35 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CarReconciliationVORowImpl extends ViewRowImpl {
    public static final int ENTITY_CARRECONCILIATIONEO = 0;
    public static final int ENTITY_SHIPMENTEO = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ReturnDate,
        DriverName,
        CoverDate,
        ToCoverDate,
        StatusName,
        DataStatus,
        ShipmentId,
        DataAgent,
        OperationAgent,
        ShipmentId1,
        UpdatedBy,
        ShipmentDate,
        ToCoverDate1,
        CoverDate1,
        RelatedShipment,
        PilotReconciliationNotes,
        HubReconciliation,
        PilotLostNew,
        ShipmentTotalLost_Rlost,
        PilotReconciliationSummary,
        TotalPilotReconciliationSummary,
        CarBalance,
        CarSummary,
        DataAgentVO1,
        AgentsROV1,
        PostingTeamAgentVO1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int RETURNDATE = AttributesEnum.ReturnDate.index();
    public static final int DRIVERNAME = AttributesEnum.DriverName.index();
    public static final int COVERDATE = AttributesEnum.CoverDate.index();
    public static final int TOCOVERDATE = AttributesEnum.ToCoverDate.index();
    public static final int STATUSNAME = AttributesEnum.StatusName.index();
    public static final int DATASTATUS = AttributesEnum.DataStatus.index();
    public static final int SHIPMENTID = AttributesEnum.ShipmentId.index();
    public static final int DATAAGENT = AttributesEnum.DataAgent.index();
    public static final int OPERATIONAGENT = AttributesEnum.OperationAgent.index();
    public static final int SHIPMENTID1 = AttributesEnum.ShipmentId1.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int SHIPMENTDATE = AttributesEnum.ShipmentDate.index();
    public static final int TOCOVERDATE1 = AttributesEnum.ToCoverDate1.index();
    public static final int COVERDATE1 = AttributesEnum.CoverDate1.index();
    public static final int RELATEDSHIPMENT = AttributesEnum.RelatedShipment.index();
    public static final int PILOTRECONCILIATIONNOTES = AttributesEnum.PilotReconciliationNotes.index();
    public static final int HUBRECONCILIATION = AttributesEnum.HubReconciliation.index();
    public static final int PILOTLOSTNEW = AttributesEnum.PilotLostNew.index();
    public static final int SHIPMENTTOTALLOST_RLOST = AttributesEnum.ShipmentTotalLost_Rlost.index();
    public static final int PILOTRECONCILIATIONSUMMARY = AttributesEnum.PilotReconciliationSummary.index();
    public static final int TOTALPILOTRECONCILIATIONSUMMARY = AttributesEnum.TotalPilotReconciliationSummary.index();
    public static final int CARBALANCE = AttributesEnum.CarBalance.index();
    public static final int CARSUMMARY = AttributesEnum.CarSummary.index();
    public static final int DATAAGENTVO1 = AttributesEnum.DataAgentVO1.index();
    public static final int AGENTSROV1 = AttributesEnum.AgentsROV1.index();
    public static final int POSTINGTEAMAGENTVO1 = AttributesEnum.PostingTeamAgentVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CarReconciliationVORowImpl() {
    }

    /**
     * Gets CarReconciliationEO entity object.
     * @return the CarReconciliationEO
     */
    public CarReconciliationEOImpl getCarReconciliationEO() {
        return (CarReconciliationEOImpl) getEntity(ENTITY_CARRECONCILIATIONEO);
    }

    /**
     * Gets ShipmentEO entity object.
     * @return the ShipmentEO
     */
    public EntityImpl getShipmentEO() {
        return (EntityImpl) getEntity(ENTITY_SHIPMENTEO);
    }

    /**
     * Gets the attribute value for RETURN_DATE using the alias name ReturnDate.
     * @return the RETURN_DATE
     */
    public Date getReturnDate() {
        return (Date) getAttributeInternal(RETURNDATE);
    }

    /**
     * Gets the attribute value for DRIVER_NAME using the alias name DriverName.
     * @return the DRIVER_NAME
     */
    public String getDriverName() {
        return (String) getAttributeInternal(DRIVERNAME);
    }

    /**
     * Gets the attribute value for COVER_DATE using the alias name CoverDate.
     * @return the COVER_DATE
     */
    public Date getCoverDate() {
        return (Date) getAttributeInternal(COVERDATE);
    }

    /**
     * Gets the attribute value for TO_COVER_DATE using the alias name ToCoverDate.
     * @return the TO_COVER_DATE
     */
    public Date getToCoverDate() {
        return (Date) getAttributeInternal(TOCOVERDATE);
    }

    /**
     * Gets the attribute value for STATUS_NAME using the alias name StatusName.
     * @return the STATUS_NAME
     */
    public String getStatusName() {
        return (String) getAttributeInternal(STATUSNAME);
    }

    /**
     * Gets the attribute value for DATA_STATUS using the alias name DataStatus.
     * @return the DATA_STATUS
     */
    public String getDataStatus() {
        return (String) getAttributeInternal(DATASTATUS);
    }

    /**
     * Gets the attribute value for SHIPMENT_ID using the alias name ShipmentId.
     * @return the SHIPMENT_ID
     */
    public BigDecimal getShipmentId() {
        return (BigDecimal) getAttributeInternal(SHIPMENTID);
    }

    /**
     * Gets the attribute value for DATA_AGENT using the alias name DataAgent.
     * @return the DATA_AGENT
     */
    public String getDataAgent() {
        return (String) getAttributeInternal(DATAAGENT);
    }

    /**
     * Sets <code>value</code> as attribute value for DATA_AGENT using the alias name DataAgent.
     * @param value value to set the DATA_AGENT
     */
    public void setDataAgent(String value) {
        setAttributeInternal(DATAAGENT, value);
    }

    /**
     * Gets the attribute value for OPERATION_AGENT using the alias name OperationAgent.
     * @return the OPERATION_AGENT
     */
    public String getOperationAgent() {
        return (String) getAttributeInternal(OPERATIONAGENT);
    }

    /**
     * Sets <code>value</code> as attribute value for OPERATION_AGENT using the alias name OperationAgent.
     * @param value value to set the OPERATION_AGENT
     */
    public void setOperationAgent(String value) {
        setAttributeInternal(OPERATIONAGENT, value);
    }

    /**
     * Gets the attribute value for SHIPMENT_ID using the alias name ShipmentId1.
     * @return the SHIPMENT_ID
     */
    public BigInteger getShipmentId1() {
        return (BigInteger) getAttributeInternal(SHIPMENTID1);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT_ID using the alias name ShipmentId1.
     * @param value value to set the SHIPMENT_ID
     */
    public void setShipmentId1(BigInteger value) {
        setAttributeInternal(SHIPMENTID1, value);
    }

    /**
     * Gets the attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @return the UPDATED_BY
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @param value value to set the UPDATED_BY
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for SHIPMENT_DATE using the alias name ShipmentDate.
     * @return the SHIPMENT_DATE
     */
    public Timestamp getShipmentDate() {
        return (Timestamp) getAttributeInternal(SHIPMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT_DATE using the alias name ShipmentDate.
     * @param value value to set the SHIPMENT_DATE
     */
    public void setShipmentDate(Timestamp value) {
        setAttributeInternal(SHIPMENTDATE, value);
    }

    /**
     * Gets the attribute value for TO_COVER_DATE_ using the alias name ToCoverDate1.
     * @return the TO_COVER_DATE_
     */
    public Timestamp getToCoverDate1() {
        return (Timestamp) getAttributeInternal(TOCOVERDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for TO_COVER_DATE_ using the alias name ToCoverDate1.
     * @param value value to set the TO_COVER_DATE_
     */
    public void setToCoverDate1(Timestamp value) {
        setAttributeInternal(TOCOVERDATE1, value);
    }

    /**
     * Gets the attribute value for COVER_DATE_ using the alias name CoverDate1.
     * @return the COVER_DATE_
     */
    public Timestamp getCoverDate1() {
        return (Timestamp) getAttributeInternal(COVERDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for COVER_DATE_ using the alias name CoverDate1.
     * @param value value to set the COVER_DATE_
     */
    public void setCoverDate1(Timestamp value) {
        setAttributeInternal(COVERDATE1, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RelatedShipment.
     */
    public RowIterator getRelatedShipment() {
        return (RowIterator) getAttributeInternal(RELATEDSHIPMENT);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PilotReconciliationNotes.
     */
    public RowIterator getPilotReconciliationNotes() {
        return (RowIterator) getAttributeInternal(PILOTRECONCILIATIONNOTES);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HubReconciliation.
     */
    public RowIterator getHubReconciliation() {
        return (RowIterator) getAttributeInternal(HUBRECONCILIATION);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PilotLostNew.
     */
    public RowIterator getPilotLostNew() {
        return (RowIterator) getAttributeInternal(PILOTLOSTNEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ShipmentTotalLost_Rlost.
     */
    public RowIterator getShipmentTotalLost_Rlost() {
        return (RowIterator) getAttributeInternal(SHIPMENTTOTALLOST_RLOST);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PilotReconciliationSummary.
     */
    public RowIterator getPilotReconciliationSummary() {
        return (RowIterator) getAttributeInternal(PILOTRECONCILIATIONSUMMARY);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TotalPilotReconciliationSummary.
     */
    public RowIterator getTotalPilotReconciliationSummary() {
        return (RowIterator) getAttributeInternal(TOTALPILOTRECONCILIATIONSUMMARY);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CarBalance.
     */
    public RowIterator getCarBalance() {
        return (RowIterator) getAttributeInternal(CARBALANCE);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CarSummary.
     */
    public RowIterator getCarSummary() {
        return (RowIterator) getAttributeInternal(CARSUMMARY);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DataAgentVO1.
     */
    public RowSet getDataAgentVO1() {
        return (RowSet) getAttributeInternal(DATAAGENTVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AgentsROV1.
     */
    public RowSet getAgentsROV1() {
        return (RowSet) getAttributeInternal(AGENTSROV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PostingTeamAgentVO1.
     */
    public RowSet getPostingTeamAgentVO1() {
        return (RowSet) getAttributeInternal(POSTINGTEAMAGENTVO1);
    }
}

