package OPERATIONPROJECT.model.BC.VO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 14 10:13:42 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DataTeamLeaderEndOfDayVORowImpl extends ViewRowImpl {
    public static final int ENTITY_DATATEAMENDOFDAYREVIEWEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AreaId,
        AreaName,
        DataAgent,
        DriverId,
        ReturnDate,
        DriverName,
        endofdayflag,
        DataAgentVO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int AREAID = AttributesEnum.AreaId.index();
    public static final int AREANAME = AttributesEnum.AreaName.index();
    public static final int DATAAGENT = AttributesEnum.DataAgent.index();
    public static final int DRIVERID = AttributesEnum.DriverId.index();
    public static final int RETURNDATE = AttributesEnum.ReturnDate.index();
    public static final int DRIVERNAME = AttributesEnum.DriverName.index();
    public static final int ENDOFDAYFLAG = AttributesEnum.endofdayflag.index();
    public static final int DATAAGENTVO1 = AttributesEnum.DataAgentVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DataTeamLeaderEndOfDayVORowImpl() {
    }
}

