package OPERATIONPROJECT.model.BC.VO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 16 13:19:52 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DataTeamAgentNotesReviewVORowImpl extends ViewRowImpl {


    public static final int ENTITY_DATATEAMNOTESREVIEWEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AreaId,
        AreaName,
        AssignDate,
        DataAgent,
        DrivId,
        DriverName,
        PilotId,
        PilotName,
        TotalAssignemnt,
        DoneContracts,
        DonePer,
        VALID,
        CheckPackageName,
        SelectedId,
        PackSelected,
        AssNotesReviewDetails,
        NewAssNotesReviewDetails;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int AREAID = AttributesEnum.AreaId.index();
    public static final int AREANAME = AttributesEnum.AreaName.index();
    public static final int ASSIGNDATE = AttributesEnum.AssignDate.index();
    public static final int DATAAGENT = AttributesEnum.DataAgent.index();
    public static final int DRIVID = AttributesEnum.DrivId.index();
    public static final int DRIVERNAME = AttributesEnum.DriverName.index();
    public static final int PILOTID = AttributesEnum.PilotId.index();
    public static final int PILOTNAME = AttributesEnum.PilotName.index();
    public static final int TOTALASSIGNEMNT = AttributesEnum.TotalAssignemnt.index();
    public static final int DONECONTRACTS = AttributesEnum.DoneContracts.index();
    public static final int DONEPER = AttributesEnum.DonePer.index();
    public static final int VALID = AttributesEnum.VALID.index();
    public static final int CHECKPACKAGENAME = AttributesEnum.CheckPackageName.index();
    public static final int SELECTEDID = AttributesEnum.SelectedId.index();
    public static final int PACKSELECTED = AttributesEnum.PackSelected.index();
    public static final int ASSNOTESREVIEWDETAILS = AttributesEnum.AssNotesReviewDetails.index();
    public static final int NEWASSNOTESREVIEWDETAILS = AttributesEnum.NewAssNotesReviewDetails.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DataTeamAgentNotesReviewVORowImpl() {
    }

    /**
     * Gets DataTeamNotesReviewEO entity object.
     * @return the DataTeamNotesReviewEO
     */
    public EntityImpl getDataTeamNotesReviewEO() {
        return (EntityImpl) getEntity(ENTITY_DATATEAMNOTESREVIEWEO);
    }

    /**
     * Gets the attribute value for AREA_ID using the alias name AreaId.
     * @return the AREA_ID
     */
    public BigDecimal getAreaId() {
        return (BigDecimal) getAttributeInternal(AREAID);
    }

    /**
     * Sets <code>value</code> as attribute value for AREA_ID using the alias name AreaId.
     * @param value value to set the AREA_ID
     */
    public void setAreaId(BigDecimal value) {
        setAttributeInternal(AREAID, value);
    }

    /**
     * Gets the attribute value for AREA_NAME using the alias name AreaName.
     * @return the AREA_NAME
     */
    public String getAreaName() {
        return (String) getAttributeInternal(AREANAME);
    }

    /**
     * Sets <code>value</code> as attribute value for AREA_NAME using the alias name AreaName.
     * @param value value to set the AREA_NAME
     */
    public void setAreaName(String value) {
        setAttributeInternal(AREANAME, value);
    }

    /**
     * Gets the attribute value for ASSIGN_DATE using the alias name AssignDate.
     * @return the ASSIGN_DATE
     */
    public Timestamp getAssignDate() {
        return (Timestamp) getAttributeInternal(ASSIGNDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSIGN_DATE using the alias name AssignDate.
     * @param value value to set the ASSIGN_DATE
     */
    public void setAssignDate(Timestamp value) {
        setAttributeInternal(ASSIGNDATE, value);
    }

    /**
     * Gets the attribute value for DATA_AGENT using the alias name DataAgent.
     * @return the DATA_AGENT
     */
    public String getDataAgent() {
        return (String) getAttributeInternal(DATAAGENT);
    }

    /**
     * Sets <code>value</code> as attribute value for DATA_AGENT using the alias name DataAgent.
     * @param value value to set the DATA_AGENT
     */
    public void setDataAgent(String value) {
        setAttributeInternal(DATAAGENT, value);
    }

    /**
     * Gets the attribute value for DRIV_ID using the alias name DrivId.
     * @return the DRIV_ID
     */
    public String getDrivId() {
        return (String) getAttributeInternal(DRIVID);
    }

    /**
     * Sets <code>value</code> as attribute value for DRIV_ID using the alias name DrivId.
     * @param value value to set the DRIV_ID
     */
    public void setDrivId(String value) {
        setAttributeInternal(DRIVID, value);
    }

    /**
     * Gets the attribute value for DRIVER_NAME using the alias name DriverName.
     * @return the DRIVER_NAME
     */
    public String getDriverName() {
        return (String) getAttributeInternal(DRIVERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DRIVER_NAME using the alias name DriverName.
     * @param value value to set the DRIVER_NAME
     */
    public void setDriverName(String value) {
        setAttributeInternal(DRIVERNAME, value);
    }

    /**
     * Gets the attribute value for PILOT_ID using the alias name PilotId.
     * @return the PILOT_ID
     */
    public String getPilotId() {
        return (String) getAttributeInternal(PILOTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PILOT_ID using the alias name PilotId.
     * @param value value to set the PILOT_ID
     */
    public void setPilotId(String value) {
        setAttributeInternal(PILOTID, value);
    }

    /**
     * Gets the attribute value for PILOT_NAME using the alias name PilotName.
     * @return the PILOT_NAME
     */
    public String getPilotName() {
        return (String) getAttributeInternal(PILOTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PILOT_NAME using the alias name PilotName.
     * @param value value to set the PILOT_NAME
     */
    public void setPilotName(String value) {
        setAttributeInternal(PILOTNAME, value);
    }

    /**
     * Gets the attribute value for TOTAL_ASSIGNEMNT using the alias name TotalAssignemnt.
     * @return the TOTAL_ASSIGNEMNT
     */
    public BigDecimal getTotalAssignemnt() {
        return (BigDecimal) getAttributeInternal(TOTALASSIGNEMNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_ASSIGNEMNT using the alias name TotalAssignemnt.
     * @param value value to set the TOTAL_ASSIGNEMNT
     */
    public void setTotalAssignemnt(BigDecimal value) {
        setAttributeInternal(TOTALASSIGNEMNT, value);
    }


    /**
     * Gets the attribute value for the calculated attribute VALID.
     * @return the VALID
     */
    public Long getVALID() {
        return (Long) getAttributeInternal(VALID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VALID.
     * @param value value to set the  VALID
     */
    public void setVALID(Long value) {
        setAttributeInternal(VALID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CheckPackageName.
     * @return the CheckPackageName
     */
    public String getCheckPackageName() {
        return (String) getAttributeInternal(CHECKPACKAGENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CheckPackageName.
     * @param value value to set the  CheckPackageName
     */
    public void setCheckPackageName(String value) {
        setAttributeInternal(CHECKPACKAGENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectedId.
     * @return the SelectedId
     */
    public String getSelectedId() {
        return (String) getAttributeInternal(SELECTEDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectedId.
     * @param value value to set the  SelectedId
     */
    public void setSelectedId(String value) {
        setAttributeInternal(SELECTEDID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PackSelected.
     * @return the PackSelected
     */
    public Long getPackSelected() {
        return (Long) getAttributeInternal(PACKSELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PackSelected.
     * @param value value to set the  PackSelected
     */
    public void setPackSelected(Long value) {
        setAttributeInternal(PACKSELECTED, value);
    }

    /**
     * Gets the attribute value for DONE_CONTRACTS using the alias name DoneContracts.
     * @return the DONE_CONTRACTS
     */
    public BigDecimal getDoneContracts() {
        return (BigDecimal) getAttributeInternal(DONECONTRACTS);
    }

    /**
     * Sets <code>value</code> as attribute value for DONE_CONTRACTS using the alias name DoneContracts.
     * @param value value to set the DONE_CONTRACTS
     */
    public void setDoneContracts(BigDecimal value) {
        setAttributeInternal(DONECONTRACTS, value);
    }

    /**
     * Gets the attribute value for DONE_PER using the alias name DonePer.
     * @return the DONE_PER
     */
    public BigDecimal getDonePer() {
        return (BigDecimal) getAttributeInternal(DONEPER);
    }

    /**
     * Sets <code>value</code> as attribute value for DONE_PER using the alias name DonePer.
     * @param value value to set the DONE_PER
     */
    public void setDonePer(BigDecimal value) {
        setAttributeInternal(DONEPER, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AssNotesReviewDetails.
     */
    public RowIterator getAssNotesReviewDetails() {
        return (RowIterator) getAttributeInternal(ASSNOTESREVIEWDETAILS);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link NewAssNotesReviewDetails.
     */
    public RowIterator getNewAssNotesReviewDetails() {
        return (RowIterator) getAttributeInternal(NEWASSNOTESREVIEWDETAILS);
    }
}

