package OPERATIONPROJECT.model.BC.VO;

import oracle.adf.share.ADFContext;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 16 12:07:19 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DataTeamAgentDashboardVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DataTeamAgentDashboardVOImpl() {
    }

    @Override
    public void prepareRowSetForQuery(ViewRowSetImpl viewRowSetImpl) {
        // TODO Implement this method
        viewRowSetImpl.ensureVariableManager().setVariableValue("P_CURRENT_USER", ADFContext.getCurrent().getSecurityContext().getUserName());
        super.prepareRowSetForQuery(viewRowSetImpl);
    }
}

