package OPERATIONPROJECT.model.BC.VO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 16 14:10:38 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DataTeamAgentEndOfDayReviewVoRowImpl extends ViewRowImpl {


    public static final int ENTITY_DATATEAMENDOFDAYREVIEWEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AreaId,
        AreaName,
        DataAgent,
        DriverId,
        DriverName,
        ReturnDate,
        DoneContracts,
        TotalContracts,
        DonePer,
        EndOfDayRevDetails;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int AREAID = AttributesEnum.AreaId.index();
    public static final int AREANAME = AttributesEnum.AreaName.index();
    public static final int DATAAGENT = AttributesEnum.DataAgent.index();
    public static final int DRIVERID = AttributesEnum.DriverId.index();
    public static final int DRIVERNAME = AttributesEnum.DriverName.index();
    public static final int RETURNDATE = AttributesEnum.ReturnDate.index();
    public static final int DONECONTRACTS = AttributesEnum.DoneContracts.index();
    public static final int TOTALCONTRACTS = AttributesEnum.TotalContracts.index();
    public static final int DONEPER = AttributesEnum.DonePer.index();
    public static final int ENDOFDAYREVDETAILS = AttributesEnum.EndOfDayRevDetails.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DataTeamAgentEndOfDayReviewVoRowImpl() {
    }

    /**
     * Gets DataTeamEndOfDayReviewEO entity object.
     * @return the DataTeamEndOfDayReviewEO
     */
    public EntityImpl getDataTeamEndOfDayReviewEO() {
        return (EntityImpl) getEntity(ENTITY_DATATEAMENDOFDAYREVIEWEO);
    }

    /**
     * Gets the attribute value for AREA_ID using the alias name AreaId.
     * @return the AREA_ID
     */
    public BigDecimal getAreaId() {
        return (BigDecimal) getAttributeInternal(AREAID);
    }

    /**
     * Sets <code>value</code> as attribute value for AREA_ID using the alias name AreaId.
     * @param value value to set the AREA_ID
     */
    public void setAreaId(BigDecimal value) {
        setAttributeInternal(AREAID, value);
    }

    /**
     * Gets the attribute value for AREA_NAME using the alias name AreaName.
     * @return the AREA_NAME
     */
    public String getAreaName() {
        return (String) getAttributeInternal(AREANAME);
    }

    /**
     * Sets <code>value</code> as attribute value for AREA_NAME using the alias name AreaName.
     * @param value value to set the AREA_NAME
     */
    public void setAreaName(String value) {
        setAttributeInternal(AREANAME, value);
    }

    /**
     * Gets the attribute value for DATA_AGENT using the alias name DataAgent.
     * @return the DATA_AGENT
     */
    public String getDataAgent() {
        return (String) getAttributeInternal(DATAAGENT);
    }

    /**
     * Sets <code>value</code> as attribute value for DATA_AGENT using the alias name DataAgent.
     * @param value value to set the DATA_AGENT
     */
    public void setDataAgent(String value) {
        setAttributeInternal(DATAAGENT, value);
    }

    /**
     * Gets the attribute value for DRIVER_ID using the alias name DriverId.
     * @return the DRIVER_ID
     */
    public String getDriverId() {
        return (String) getAttributeInternal(DRIVERID);
    }

    /**
     * Sets <code>value</code> as attribute value for DRIVER_ID using the alias name DriverId.
     * @param value value to set the DRIVER_ID
     */
    public void setDriverId(String value) {
        setAttributeInternal(DRIVERID, value);
    }

    /**
     * Gets the attribute value for DRIVER_NAME using the alias name DriverName.
     * @return the DRIVER_NAME
     */
    public String getDriverName() {
        return (String) getAttributeInternal(DRIVERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DRIVER_NAME using the alias name DriverName.
     * @param value value to set the DRIVER_NAME
     */
    public void setDriverName(String value) {
        setAttributeInternal(DRIVERNAME, value);
    }

    /**
     * Gets the attribute value for RETURN_DATE using the alias name ReturnDate.
     * @return the RETURN_DATE
     */
    public Timestamp getReturnDate() {
        return (Timestamp) getAttributeInternal(RETURNDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RETURN_DATE using the alias name ReturnDate.
     * @param value value to set the RETURN_DATE
     */
    public void setReturnDate(Timestamp value) {
        setAttributeInternal(RETURNDATE, value);
    }

    /**
     * Gets the attribute value for DONE_CONTRACTS using the alias name DoneContracts.
     * @return the DONE_CONTRACTS
     */
    public BigDecimal getDoneContracts() {
        return (BigDecimal) getAttributeInternal(DONECONTRACTS);
    }

    /**
     * Sets <code>value</code> as attribute value for DONE_CONTRACTS using the alias name DoneContracts.
     * @param value value to set the DONE_CONTRACTS
     */
    public void setDoneContracts(BigDecimal value) {
        setAttributeInternal(DONECONTRACTS, value);
    }

    /**
     * Gets the attribute value for DONE_PER using the alias name DonePer.
     * @return the DONE_PER
     */
    public BigDecimal getDonePer() {
        return (BigDecimal) getAttributeInternal(DONEPER);
    }

    /**
     * Sets <code>value</code> as attribute value for DONE_PER using the alias name DonePer.
     * @param value value to set the DONE_PER
     */
    public void setDonePer(BigDecimal value) {
        setAttributeInternal(DONEPER, value);
    }

    /**
     * Gets the attribute value for TOTAL_CONTRACTS using the alias name TotalContracts.
     * @return the TOTAL_CONTRACTS
     */
    public BigDecimal getTotalContracts() {
        return (BigDecimal) getAttributeInternal(TOTALCONTRACTS);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_CONTRACTS using the alias name TotalContracts.
     * @param value value to set the TOTAL_CONTRACTS
     */
    public void setTotalContracts(BigDecimal value) {
        setAttributeInternal(TOTALCONTRACTS, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EndOfDayRevDetails.
     */
    public RowIterator getEndOfDayRevDetails() {
        return (RowIterator) getAttributeInternal(ENDOFDAYREVDETAILS);
    }
}

