package OPERATIONPROJECT.model.BC.VO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 16 12:07:18 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DataTeamAgentDashboardVORowImpl extends ViewRowImpl {


    public static final int ENTITY_DATATEAMLEADERDASHBOARDEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AssignDate,
        CompletedCount,
        CompletedPer,
        DataAgent,
        DataAgentName,
        TotalAssignemnt,
        DataDate,
        WorkType,
        AreaId,
        DriverId,
        AreaName,
        DriverName;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ASSIGNDATE = AttributesEnum.AssignDate.index();
    public static final int COMPLETEDCOUNT = AttributesEnum.CompletedCount.index();
    public static final int COMPLETEDPER = AttributesEnum.CompletedPer.index();
    public static final int DATAAGENT = AttributesEnum.DataAgent.index();
    public static final int DATAAGENTNAME = AttributesEnum.DataAgentName.index();
    public static final int TOTALASSIGNEMNT = AttributesEnum.TotalAssignemnt.index();
    public static final int DATADATE = AttributesEnum.DataDate.index();
    public static final int WORKTYPE = AttributesEnum.WorkType.index();
    public static final int AREAID = AttributesEnum.AreaId.index();
    public static final int DRIVERID = AttributesEnum.DriverId.index();
    public static final int AREANAME = AttributesEnum.AreaName.index();
    public static final int DRIVERNAME = AttributesEnum.DriverName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DataTeamAgentDashboardVORowImpl() {
    }
}

