package OPERATIONPROJECT.model.BC.VO;

import OPERATIONPROJECT.model.BC.EO.CarReconciliationEOImpl;

import java.math.BigDecimal;

import java.sql.Time;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 20 13:16:24 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DataTeamAgentCarReconciliationVORowImpl extends ViewRowImpl {


    public static final int ENTITY_CARRECONCILIATIONEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CoverDate,
        DataAgent,
        DataStatus,
        DriverName,
        OperationAgent,
        ReturnDate,
        ShipmentId,
        StatusName,
        ToCoverDate,
        PilotCoverEdited,
        PilotCoverComment,
        CarStatusId,
        ShipmentDate,
        ToCoverDate1,
        CoverDate1,
        RelatedShipment,
        ContractsReview,
        ReconciliationNotes,
        CarReconHubRecon,
        CarReconPilotsLostNew,
        CarLostNew,
        PilotReconciliationSummary,
        CarReconCarSummary,
        RelatedAss1,
        RelatedCR1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COVERDATE = AttributesEnum.CoverDate.index();
    public static final int DATAAGENT = AttributesEnum.DataAgent.index();
    public static final int DATASTATUS = AttributesEnum.DataStatus.index();
    public static final int DRIVERNAME = AttributesEnum.DriverName.index();
    public static final int OPERATIONAGENT = AttributesEnum.OperationAgent.index();
    public static final int RETURNDATE = AttributesEnum.ReturnDate.index();
    public static final int SHIPMENTID = AttributesEnum.ShipmentId.index();
    public static final int STATUSNAME = AttributesEnum.StatusName.index();
    public static final int TOCOVERDATE = AttributesEnum.ToCoverDate.index();
    public static final int PILOTCOVEREDITED = AttributesEnum.PilotCoverEdited.index();
    public static final int PILOTCOVERCOMMENT = AttributesEnum.PilotCoverComment.index();
    public static final int CARSTATUSID = AttributesEnum.CarStatusId.index();
    public static final int SHIPMENTDATE = AttributesEnum.ShipmentDate.index();
    public static final int TOCOVERDATE1 = AttributesEnum.ToCoverDate1.index();
    public static final int COVERDATE1 = AttributesEnum.CoverDate1.index();
    public static final int RELATEDSHIPMENT = AttributesEnum.RelatedShipment.index();
    public static final int CONTRACTSREVIEW = AttributesEnum.ContractsReview.index();
    public static final int RECONCILIATIONNOTES = AttributesEnum.ReconciliationNotes.index();
    public static final int CARRECONHUBRECON = AttributesEnum.CarReconHubRecon.index();
    public static final int CARRECONPILOTSLOSTNEW = AttributesEnum.CarReconPilotsLostNew.index();
    public static final int CARLOSTNEW = AttributesEnum.CarLostNew.index();
    public static final int PILOTRECONCILIATIONSUMMARY = AttributesEnum.PilotReconciliationSummary.index();
    public static final int CARRECONCARSUMMARY = AttributesEnum.CarReconCarSummary.index();
    public static final int RELATEDASS1 = AttributesEnum.RelatedAss1.index();
    public static final int RELATEDCR1 = AttributesEnum.RelatedCR1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DataTeamAgentCarReconciliationVORowImpl() {
    }

    /**
     * Gets CarReconciliationEO entity object.
     * @return the CarReconciliationEO
     */
    public CarReconciliationEOImpl getCarReconciliationEO() {
        return (CarReconciliationEOImpl) getEntity(ENTITY_CARRECONCILIATIONEO);
    }

    /**
     * Gets the attribute value for COVER_DATE using the alias name CoverDate.
     * @return the COVER_DATE
     */
    public Date getCoverDate() {
        return (Date) getAttributeInternal(COVERDATE);
    }

    /**
     * Gets the attribute value for DATA_AGENT using the alias name DataAgent.
     * @return the DATA_AGENT
     */
    public String getDataAgent() {
        return (String) getAttributeInternal(DATAAGENT);
    }

    /**
     * Sets <code>value</code> as attribute value for DATA_AGENT using the alias name DataAgent.
     * @param value value to set the DATA_AGENT
     */
    public void setDataAgent(String value) {
        setAttributeInternal(DATAAGENT, value);
    }

    /**
     * Gets the attribute value for DATA_STATUS using the alias name DataStatus.
     * @return the DATA_STATUS
     */
    public String getDataStatus() {
        return (String) getAttributeInternal(DATASTATUS);
    }

    /**
     * Gets the attribute value for DRIVER_NAME using the alias name DriverName.
     * @return the DRIVER_NAME
     */
    public String getDriverName() {
        return (String) getAttributeInternal(DRIVERNAME);
    }

    /**
     * Gets the attribute value for OPERATION_AGENT using the alias name OperationAgent.
     * @return the OPERATION_AGENT
     */
    public String getOperationAgent() {
        return (String) getAttributeInternal(OPERATIONAGENT);
    }

    /**
     * Sets <code>value</code> as attribute value for OPERATION_AGENT using the alias name OperationAgent.
     * @param value value to set the OPERATION_AGENT
     */
    public void setOperationAgent(String value) {
        setAttributeInternal(OPERATIONAGENT, value);
    }

    /**
     * Gets the attribute value for RETURN_DATE using the alias name ReturnDate.
     * @return the RETURN_DATE
     */
    public Date getReturnDate() {
        return (Date) getAttributeInternal(RETURNDATE);
    }

    /**
     * Gets the attribute value for SHIPMENT_ID using the alias name ShipmentId.
     * @return the SHIPMENT_ID
     */
    public BigDecimal getShipmentId() {
        return (BigDecimal) getAttributeInternal(SHIPMENTID);
    }

    /**
     * Gets the attribute value for STATUS_NAME using the alias name StatusName.
     * @return the STATUS_NAME
     */
    public String getStatusName() {
        return (String) getAttributeInternal(STATUSNAME);
    }

    /**
     * Gets the attribute value for TO_COVER_DATE using the alias name ToCoverDate.
     * @return the TO_COVER_DATE
     */
    public Date getToCoverDate() {
        return (Date) getAttributeInternal(TOCOVERDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute PilotCoverEdited.
     * @return the PilotCoverEdited
     */
    public BigDecimal getPilotCoverEdited() {
        return (BigDecimal) getAttributeInternal(PILOTCOVEREDITED);
    }

    /**
     * Gets the attribute value for the calculated attribute PilotCoverComment.
     * @return the PilotCoverComment
     */
    public String getPilotCoverComment() {
        return (String) getAttributeInternal(PILOTCOVERCOMMENT);
    }

    /**
     * Gets the attribute value for the calculated attribute CarStatusId.
     * @return the CarStatusId
     */
    public BigDecimal getCarStatusId() {
        return (BigDecimal) getAttributeInternal(CARSTATUSID);
    }

    /**
     * Gets the attribute value for COVER_DATE_ using the alias name CoverDate1.
     * @return the COVER_DATE_
     */
    public Timestamp getCoverDate1() {
        return (Timestamp) getAttributeInternal(COVERDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for COVER_DATE_ using the alias name CoverDate1.
     * @param value value to set the COVER_DATE_
     */
    public void setCoverDate1(Timestamp value) {
        setAttributeInternal(COVERDATE1, value);
    }

    /**
     * Gets the attribute value for SHIPMENT_DATE using the alias name ShipmentDate.
     * @return the SHIPMENT_DATE
     */
    public Timestamp getShipmentDate() {
        return (Timestamp) getAttributeInternal(SHIPMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT_DATE using the alias name ShipmentDate.
     * @param value value to set the SHIPMENT_DATE
     */
    public void setShipmentDate(Timestamp value) {
        setAttributeInternal(SHIPMENTDATE, value);
    }

    /**
     * Gets the attribute value for TO_COVER_DATE_ using the alias name ToCoverDate1.
     * @return the TO_COVER_DATE_
     */
    public Timestamp getToCoverDate1() {
        return (Timestamp) getAttributeInternal(TOCOVERDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for TO_COVER_DATE_ using the alias name ToCoverDate1.
     * @param value value to set the TO_COVER_DATE_
     */
    public void setToCoverDate1(Timestamp value) {
        setAttributeInternal(TOCOVERDATE1, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RelatedShipment.
     */
    public RowIterator getRelatedShipment() {
        return (RowIterator) getAttributeInternal(RELATEDSHIPMENT);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ContractsReview.
     */
    public RowIterator getContractsReview() {
        return (RowIterator) getAttributeInternal(CONTRACTSREVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ReconciliationNotes.
     */
    public RowIterator getReconciliationNotes() {
        return (RowIterator) getAttributeInternal(RECONCILIATIONNOTES);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CarReconHubRecon.
     */
    public RowIterator getCarReconHubRecon() {
        return (RowIterator) getAttributeInternal(CARRECONHUBRECON);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CarReconPilotsLostNew.
     */
    public RowIterator getCarReconPilotsLostNew() {
        return (RowIterator) getAttributeInternal(CARRECONPILOTSLOSTNEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CarLostNew.
     */
    public RowIterator getCarLostNew() {
        return (RowIterator) getAttributeInternal(CARLOSTNEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PilotReconciliationSummary.
     */
    public RowIterator getPilotReconciliationSummary() {
        return (RowIterator) getAttributeInternal(PILOTRECONCILIATIONSUMMARY);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CarReconCarSummary.
     */
    public RowIterator getCarReconCarSummary() {
        return (RowIterator) getAttributeInternal(CARRECONCARSUMMARY);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RelatedAss1.
     */
    public RowIterator getRelatedAss1() {
        return (RowIterator) getAttributeInternal(RELATEDASS1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RelatedCR1.
     */
    public RowIterator getRelatedCR1() {
        return (RowIterator) getAttributeInternal(RELATEDCR1);
    }
}

