package OPERATIONPROJECT.model.BC.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 27 17:59:36 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EligibleRLostHeaderVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EligibleRLostHeaderVOImpl() {
    }
}

