package OPERATIONPROJECT.model.BC.VO;

import java.math.BigDecimal;
import java.math.BigInteger;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 27 17:59:36 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EligibleRLostHeaderVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ProductName,
        ShipmentId,
        ProductId,
        RlostEligble,
        OutQuantity,
        ExpectedReturned,
        QtyReturned,
        ProductBalance,
        DirtyBalance,
        HubClean,
        DataClean,
        HubDirty,
        DataDirty,
        HubCancel,
        DataCancel,
        HubNew,
        DataNew,
        LostNew,
        HubRlost,
        ReconciledRlost,
        NetRlost,
        DirtyValue,
        LostValue;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int PRODUCTNAME = AttributesEnum.ProductName.index();
    public static final int SHIPMENTID = AttributesEnum.ShipmentId.index();
    public static final int PRODUCTID = AttributesEnum.ProductId.index();
    public static final int RLOSTELIGBLE = AttributesEnum.RlostEligble.index();
    public static final int OUTQUANTITY = AttributesEnum.OutQuantity.index();
    public static final int EXPECTEDRETURNED = AttributesEnum.ExpectedReturned.index();
    public static final int QTYRETURNED = AttributesEnum.QtyReturned.index();
    public static final int PRODUCTBALANCE = AttributesEnum.ProductBalance.index();
    public static final int DIRTYBALANCE = AttributesEnum.DirtyBalance.index();
    public static final int HUBCLEAN = AttributesEnum.HubClean.index();
    public static final int DATACLEAN = AttributesEnum.DataClean.index();
    public static final int HUBDIRTY = AttributesEnum.HubDirty.index();
    public static final int DATADIRTY = AttributesEnum.DataDirty.index();
    public static final int HUBCANCEL = AttributesEnum.HubCancel.index();
    public static final int DATACANCEL = AttributesEnum.DataCancel.index();
    public static final int HUBNEW = AttributesEnum.HubNew.index();
    public static final int DATANEW = AttributesEnum.DataNew.index();
    public static final int LOSTNEW = AttributesEnum.LostNew.index();
    public static final int HUBRLOST = AttributesEnum.HubRlost.index();
    public static final int RECONCILEDRLOST = AttributesEnum.ReconciledRlost.index();
    public static final int NETRLOST = AttributesEnum.NetRlost.index();
    public static final int DIRTYVALUE = AttributesEnum.DirtyValue.index();
    public static final int LOSTVALUE = AttributesEnum.LostValue.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EligibleRLostHeaderVORowImpl() {
    }
}

