package OPERATIONPROJECT.model.BC.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 16 14:23:40 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EndOfDayRevDetailsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EndOfDayRevDetailsVOImpl() {
    }
}

