package OPERATIONPROJECT.model.BC.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 31 14:25:33 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductContractVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProductContractVOImpl() {
    }

    /**
     * Returns the bind variable value for P_CARDNO.
     * @return bind variable value for P_CARDNO
     */
    public String getP_CARDNO() {
        return (String) getNamedWhereClauseParam("P_CARDNO");
    }

    /**
     * Sets <code>value</code> for bind variable P_CARDNO.
     * @param value value to bind as P_CARDNO
     */
    public void setP_CARDNO(String value) {
        setNamedWhereClauseParam("P_CARDNO", value);
    }
}

