package OPERATIONPROJECT.model.BC.VO;

import OPERATIONPROJECT.model.BC.EO.ProductLostRlostEOImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import oracle.adf.share.ADFContext;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 27 21:08:04 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductLostRlostVORowImpl extends ViewRowImpl {
    public static final int ENTITY_PRODUCTLOSTRLOSTEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        ShipmentId,
        LostDate,
        ProductId,
        LostQuantity,
        Status,
        QtyReturned,
        ReturnDate,
        PilotId,
        ReturnAgent,
        LostAgent,
        Type,
        LostStatusVO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int SHIPMENTID = AttributesEnum.ShipmentId.index();
    public static final int LOSTDATE = AttributesEnum.LostDate.index();
    public static final int PRODUCTID = AttributesEnum.ProductId.index();
    public static final int LOSTQUANTITY = AttributesEnum.LostQuantity.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int QTYRETURNED = AttributesEnum.QtyReturned.index();
    public static final int RETURNDATE = AttributesEnum.ReturnDate.index();
    public static final int PILOTID = AttributesEnum.PilotId.index();
    public static final int RETURNAGENT = AttributesEnum.ReturnAgent.index();
    public static final int LOSTAGENT = AttributesEnum.LostAgent.index();
    public static final int TYPE = AttributesEnum.Type.index();
    public static final int LOSTSTATUSVO1 = AttributesEnum.LostStatusVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProductLostRlostVORowImpl() {
    }

    /**
     * Gets ProductLostRlostEO entity object.
     * @return the ProductLostRlostEO
     */
    public ProductLostRlostEOImpl getProductLostRlostEO() {
        return (ProductLostRlostEOImpl) getEntity(ENTITY_PRODUCTLOSTRLOSTEO);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public BigDecimal getId() {
        return (BigDecimal) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(BigDecimal value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for SHIPMENT_ID using the alias name ShipmentId.
     * @return the SHIPMENT_ID
     */
    public BigDecimal getShipmentId() {
        return (BigDecimal) getAttributeInternal(SHIPMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT_ID using the alias name ShipmentId.
     * @param value value to set the SHIPMENT_ID
     */
    public void setShipmentId(BigDecimal value) {
        setAttributeInternal(SHIPMENTID, value);
    }

    /**
     * Gets the attribute value for LOST_DATE using the alias name LostDate.
     * @return the LOST_DATE
     */
    public Timestamp getLostDate() {
        return (Timestamp) getAttributeInternal(LOSTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOST_DATE using the alias name LostDate.
     * @param value value to set the LOST_DATE
     */
    public void setLostDate(Timestamp value) {
        setAttributeInternal(LOSTDATE, value);
    }

    /**
     * Gets the attribute value for PRODUCT_ID using the alias name ProductId.
     * @return the PRODUCT_ID
     */
    public String getProductId() {
        return (String) getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_ID using the alias name ProductId.
     * @param value value to set the PRODUCT_ID
     */
    public void setProductId(String value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for LOST_QUANTITY using the alias name LostQuantity.
     * @return the LOST_QUANTITY
     */
    public BigDecimal getLostQuantity() {
        return (BigDecimal) getAttributeInternal(LOSTQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for LOST_QUANTITY using the alias name LostQuantity.
     * @param value value to set the LOST_QUANTITY
     */
    public void setLostQuantity(BigDecimal value) {
        setAttributeInternal(LOSTQUANTITY, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public BigDecimal getStatus() {
        return (BigDecimal) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(BigDecimal value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for QTY_RETURNED using the alias name QtyReturned.
     * @return the QTY_RETURNED
     */
    public BigDecimal getQtyReturned() {
        return (BigDecimal) getAttributeInternal(QTYRETURNED);
    }

    /**
     * Sets <code>value</code> as attribute value for QTY_RETURNED using the alias name QtyReturned.
     * @param value value to set the QTY_RETURNED
     */
    public void setQtyReturned(BigDecimal value) {
        if(value != null || Integer.parseInt(value.toString()) !=0){
            setReturnDate(new Timestamp(System.currentTimeMillis()));
            setReturnAgent(ADFContext.getCurrent().getSecurityContext().getUserName());
            setStatus(new BigDecimal("2"));
        }
        else{
            setReturnDate(null);
            setReturnAgent(null);
            setStatus(new BigDecimal("1"));
        }
        setAttributeInternal(QTYRETURNED, value);
    }

    /**
     * Gets the attribute value for RETURN_DATE using the alias name ReturnDate.
     * @return the RETURN_DATE
     */
    public Timestamp getReturnDate() {
        return (Timestamp) getAttributeInternal(RETURNDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RETURN_DATE using the alias name ReturnDate.
     * @param value value to set the RETURN_DATE
     */
    public void setReturnDate(Timestamp value) {
        setAttributeInternal(RETURNDATE, value);
    }

    /**
     * Gets the attribute value for PILOT_ID using the alias name PilotId.
     * @return the PILOT_ID
     */
    public String getPilotId() {
        return (String) getAttributeInternal(PILOTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PILOT_ID using the alias name PilotId.
     * @param value value to set the PILOT_ID
     */
    public void setPilotId(String value) {
        setAttributeInternal(PILOTID, value);
    }

    /**
     * Gets the attribute value for RETURN_AGENT using the alias name ReturnAgent.
     * @return the RETURN_AGENT
     */
    public String getReturnAgent() {
        return (String) getAttributeInternal(RETURNAGENT);
    }

    /**
     * Sets <code>value</code> as attribute value for RETURN_AGENT using the alias name ReturnAgent.
     * @param value value to set the RETURN_AGENT
     */
    public void setReturnAgent(String value) {
        setAttributeInternal(RETURNAGENT, value);
    }

    /**
     * Gets the attribute value for LOST_AGENT using the alias name LostAgent.
     * @return the LOST_AGENT
     */
    public String getLostAgent() {
        return (String) getAttributeInternal(LOSTAGENT);
    }

    /**
     * Sets <code>value</code> as attribute value for LOST_AGENT using the alias name LostAgent.
     * @param value value to set the LOST_AGENT
     */
    public void setLostAgent(String value) {
        setAttributeInternal(LOSTAGENT, value);
    }

    /**
     * Gets the attribute value for TYPE using the alias name Type.
     * @return the TYPE
     */
    public BigDecimal getType() {
        return (BigDecimal) getAttributeInternal(TYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPE using the alias name Type.
     * @param value value to set the TYPE
     */
    public void setType(BigDecimal value) {
        setAttributeInternal(TYPE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LostStatusVO1.
     */
    public RowSet getLostStatusVO1() {
        return (RowSet) getAttributeInternal(LOSTSTATUSVO1);
    }
}

