package OPERATIONPROJECT.model.BC.VO;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 27 21:08:10 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductLostRlostVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProductLostRlostVOImpl() {
    }

    /**
     * Returns the bind variable value for P_SHIPMENT_ID.
     * @return bind variable value for P_SHIPMENT_ID
     */
    public BigDecimal getP_SHIPMENT_ID() {
        return (BigDecimal) getNamedWhereClauseParam("P_SHIPMENT_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_SHIPMENT_ID.
     * @param value value to bind as P_SHIPMENT_ID
     */
    public void setP_SHIPMENT_ID(BigDecimal value) {
        setNamedWhereClauseParam("P_SHIPMENT_ID", value);
    }

    /**
     * Returns the bind variable value for P_PRODUCT_ID.
     * @return bind variable value for P_PRODUCT_ID
     */
    public String getP_PRODUCT_ID() {
        return (String) getNamedWhereClauseParam("P_PRODUCT_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_PRODUCT_ID.
     * @param value value to bind as P_PRODUCT_ID
     */
    public void setP_PRODUCT_ID(String value) {
        setNamedWhereClauseParam("P_PRODUCT_ID", value);
    }

    /**
     * Returns the bind variable value for P_PILOT_ID.
     * @return bind variable value for P_PILOT_ID
     */
    public String getP_PILOT_ID() {
        return (String) getNamedWhereClauseParam("P_PILOT_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_PILOT_ID.
     * @param value value to bind as P_PILOT_ID
     */
    public void setP_PILOT_ID(String value) {
        setNamedWhereClauseParam("P_PILOT_ID", value);
    }
}

