package OPERATIONPROJECT.model.BC.VO;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 31 14:25:30 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductContractVORowImpl extends ViewRowImpl {


    public static final int ENTITY_PRODUCTCONTRACTEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Active,
        ActiveFrom,
        ActiveTo,
        Cancelled,
        CardNo,
        Id,
        New11,
        PNew,
        PackageNo,
        PackageVersion,
        Paid,
        PartialSubmit,
        PendingConfirmation,
        ProductId,
        ProductSerial,
        ProductSku,
        Quantity,
        TreatmentId,
        UnitPrice,
        UpdateTime,
        UpdatedBy,
        PaidSel,
        ActiveSel,
        CancelledSel,
        NewPackFlag,
        AssNotesReviewDetails,
        NewCancelSalesContracts,
        ProductDataVO1,
        TreatmentTypesVO1,
        ProductPackageVO1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int ACTIVEFROM = AttributesEnum.ActiveFrom.index();
    public static final int ACTIVETO = AttributesEnum.ActiveTo.index();
    public static final int CANCELLED = AttributesEnum.Cancelled.index();
    public static final int CARDNO = AttributesEnum.CardNo.index();
    public static final int ID = AttributesEnum.Id.index();
    public static final int NEW11 = AttributesEnum.New11.index();
    public static final int PNEW = AttributesEnum.PNew.index();
    public static final int PACKAGENO = AttributesEnum.PackageNo.index();
    public static final int PACKAGEVERSION = AttributesEnum.PackageVersion.index();
    public static final int PAID = AttributesEnum.Paid.index();
    public static final int PARTIALSUBMIT = AttributesEnum.PartialSubmit.index();
    public static final int PENDINGCONFIRMATION = AttributesEnum.PendingConfirmation.index();
    public static final int PRODUCTID = AttributesEnum.ProductId.index();
    public static final int PRODUCTSERIAL = AttributesEnum.ProductSerial.index();
    public static final int PRODUCTSKU = AttributesEnum.ProductSku.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int TREATMENTID = AttributesEnum.TreatmentId.index();
    public static final int UNITPRICE = AttributesEnum.UnitPrice.index();
    public static final int UPDATETIME = AttributesEnum.UpdateTime.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int PAIDSEL = AttributesEnum.PaidSel.index();
    public static final int ACTIVESEL = AttributesEnum.ActiveSel.index();
    public static final int CANCELLEDSEL = AttributesEnum.CancelledSel.index();
    public static final int NEWPACKFLAG = AttributesEnum.NewPackFlag.index();
    public static final int ASSNOTESREVIEWDETAILS = AttributesEnum.AssNotesReviewDetails.index();
    public static final int NEWCANCELSALESCONTRACTS = AttributesEnum.NewCancelSalesContracts.index();
    public static final int PRODUCTDATAVO1 = AttributesEnum.ProductDataVO1.index();
    public static final int TREATMENTTYPESVO1 = AttributesEnum.TreatmentTypesVO1.index();
    public static final int PRODUCTPACKAGEVO1 = AttributesEnum.ProductPackageVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProductContractVORowImpl() {
    }
}

