package OPERATIONPROJECT.model.BC.EO;

import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 17 06:51:32 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductContractDeliveryEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        CardNo,
        PackageId,
        PackageVersion,
        PackageNo,
        ProductId,
        TreatmentId,
        ProductSku,
        Quantity,
        QuantityReplaced,
        QuantityDirty,
        Price,
        QuantityCancelled,
        AssignmentId,
        Aid,
        ProductConId,
        InsertTime,
        LastUpdated,
        AssignId,
        DeliveryType,
        SerialNum;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int CARDNO = AttributesEnum.CardNo.index();
    public static final int PACKAGEID = AttributesEnum.PackageId.index();
    public static final int PACKAGEVERSION = AttributesEnum.PackageVersion.index();
    public static final int PACKAGENO = AttributesEnum.PackageNo.index();
    public static final int PRODUCTID = AttributesEnum.ProductId.index();
    public static final int TREATMENTID = AttributesEnum.TreatmentId.index();
    public static final int PRODUCTSKU = AttributesEnum.ProductSku.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int QUANTITYREPLACED = AttributesEnum.QuantityReplaced.index();
    public static final int QUANTITYDIRTY = AttributesEnum.QuantityDirty.index();
    public static final int PRICE = AttributesEnum.Price.index();
    public static final int QUANTITYCANCELLED = AttributesEnum.QuantityCancelled.index();
    public static final int ASSIGNMENTID = AttributesEnum.AssignmentId.index();
    public static final int AID = AttributesEnum.Aid.index();
    public static final int PRODUCTCONID = AttributesEnum.ProductConId.index();
    public static final int INSERTTIME = AttributesEnum.InsertTime.index();
    public static final int LASTUPDATED = AttributesEnum.LastUpdated.index();
    public static final int ASSIGNID = AttributesEnum.AssignId.index();
    public static final int DELIVERYTYPE = AttributesEnum.DeliveryType.index();
    public static final int SERIALNUM = AttributesEnum.SerialNum.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProductContractDeliveryEOImpl() {
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[] { id });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("OPERATIONPROJECT.model.BC.EO.ProductContractDeliveryEO");
    }


}

