package OPERATIONPROJECT.model.BC.EO;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 17 07:04:03 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PromosDeliveryEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        ProductName,
        ProductSku,
        AssignDate,
        CardNo,
        AreaId,
        Quantity,
        DeliveryFlag,
        NextDeliveryDate,
        Price,
        PromoPrice;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int PRODUCTNAME = AttributesEnum.ProductName.index();
    public static final int PRODUCTSKU = AttributesEnum.ProductSku.index();
    public static final int ASSIGNDATE = AttributesEnum.AssignDate.index();
    public static final int CARDNO = AttributesEnum.CardNo.index();
    public static final int AREAID = AttributesEnum.AreaId.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int DELIVERYFLAG = AttributesEnum.DeliveryFlag.index();
    public static final int NEXTDELIVERYDATE = AttributesEnum.NextDeliveryDate.index();
    public static final int PRICE = AttributesEnum.Price.index();
    public static final int PROMOPRICE = AttributesEnum.PromoPrice.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PromosDeliveryEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("OPERATIONPROJECT.model.BC.EO.PromosDeliveryEO");
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public DBSequence getId() {
        return (DBSequence) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for ProductName, using the alias name ProductName.
     * @return the value of ProductName
     */
    public String getProductName() {
        return (String) getAttributeInternal(PRODUCTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductName.
     * @param value value to set the ProductName
     */
    public void setProductName(String value) {
        setAttributeInternal(PRODUCTNAME, value);
    }

    /**
     * Gets the attribute value for ProductSku, using the alias name ProductSku.
     * @return the value of ProductSku
     */
    public String getProductSku() {
        return (String) getAttributeInternal(PRODUCTSKU);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductSku.
     * @param value value to set the ProductSku
     */
    public void setProductSku(String value) {
        setAttributeInternal(PRODUCTSKU, value);
    }

    /**
     * Gets the attribute value for AssignDate, using the alias name AssignDate.
     * @return the value of AssignDate
     */
    public Date getAssignDate() {
        return (Date) getAttributeInternal(ASSIGNDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AssignDate.
     * @param value value to set the AssignDate
     */
    public void setAssignDate(Date value) {
        setAttributeInternal(ASSIGNDATE, value);
    }

    /**
     * Gets the attribute value for CardNo, using the alias name CardNo.
     * @return the value of CardNo
     */
    public Long getCardNo() {
        return (Long) getAttributeInternal(CARDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CardNo.
     * @param value value to set the CardNo
     */
    public void setCardNo(Long value) {
        setAttributeInternal(CARDNO, value);
    }

    /**
     * Gets the attribute value for AreaId, using the alias name AreaId.
     * @return the value of AreaId
     */
    public Long getAreaId() {
        return (Long) getAttributeInternal(AREAID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AreaId.
     * @param value value to set the AreaId
     */
    public void setAreaId(Long value) {
        setAttributeInternal(AREAID, value);
    }

    /**
     * Gets the attribute value for Quantity, using the alias name Quantity.
     * @return the value of Quantity
     */
    public Long getQuantity() {
        return (Long) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Quantity.
     * @param value value to set the Quantity
     */
    public void setQuantity(Long value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for DeliveryFlag, using the alias name DeliveryFlag.
     * @return the value of DeliveryFlag
     */
    public Long getDeliveryFlag() {
        return (Long) getAttributeInternal(DELIVERYFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryFlag.
     * @param value value to set the DeliveryFlag
     */
    public void setDeliveryFlag(Long value) {
        setAttributeInternal(DELIVERYFLAG, value);
    }

    /**
     * Gets the attribute value for NextDeliveryDate, using the alias name NextDeliveryDate.
     * @return the value of NextDeliveryDate
     */
    public Timestamp getNextDeliveryDate() {
        return (Timestamp) getAttributeInternal(NEXTDELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NextDeliveryDate.
     * @param value value to set the NextDeliveryDate
     */
    public void setNextDeliveryDate(Timestamp value) {
        setAttributeInternal(NEXTDELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for Price, using the alias name Price.
     * @return the value of Price
     */
    public Long getPrice() {
        return (Long) getAttributeInternal(PRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Price.
     * @param value value to set the Price
     */
    public void setPrice(Long value) {
        PrmosLookupEOImpl promo_obj=new PrmosLookupEOImpl();
        setAttributeInternal(PRICE, promo_obj.getSellingPrice());
    }

    /**
     * Gets the attribute value for PromoPrice, using the alias name PromoPrice.
     * @return the value of PromoPrice
     */
    public Long getPromoPrice() {
        return (Long) getAttributeInternal(PROMOPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PromoPrice.
     * @param value value to set the PromoPrice
     */
    public void setPromoPrice(Long value) {
        setAttributeInternal(PROMOPRICE, value);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[] { id });
    }


}

