package OPERATIONPROJECT.model.BC.EO;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 28 12:24:04 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WeekDaysEODefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public WeekDaysEODefImpl() {
    }
}

