package OPERATIONPROJECT.model.BC.EO;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 28 12:23:08 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WeekDaysEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        WorkingDate,
        DayName;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int WORKINGDATE = AttributesEnum.WorkingDate.index();
    public static final int DAYNAME = AttributesEnum.DayName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WeekDaysEOImpl() {
    }

    /**
     * @param workingDate key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Date workingDate) {
        return new Key(new Object[] { workingDate });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("OPERATIONPROJECT.model.BC.EO.WeekDaysEO");
    }


}

