package OPERATIONPROJECT.model.BC.AM.common;

import java.util.ArrayList;
import java.util.HashMap;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Key;
import oracle.jbo.Row;

import oracle.jheadstart.model.adfbc.service.common.JhsModelService;
import oracle.jheadstart.model.adfbc.v2.JhsApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 30 11:30:05 EET 2020
// ---------------------------------------------------------------------
public interface AppModuleAM extends JhsApplicationModule, ApplicationModule {
    void applyBindParams(String voUsage, ArrayList args);


    void applyBindParams(String voUsage, HashMap args, Boolean doRequeryWhenParamsChanged);

    String getJhsOrgKey();

    JhsModelService getNestedJhsModelService();

    void processParentShuttle(Row parentRow, String childUsage, String unselectedListUsage, Key[] oldSelectedKeys,
                              Key[] newSelectedKeys, HashMap parentChildRefAttrs);

    void processIntersectionShuttle(Row parent1Row, String intersectionUsage, String parent2Usage,
                                    Key[] oldSelectedKeys, Key[] newSelectedKeys, HashMap parent2ChildRefAttrs);

    void setRangeStart(String viewObjectUsage, String rangeStart);

    void queryByKeyValue(String viewObjectUsage, String keyValue);


    void setCurrentRowWithKeyValue(String viewObjectUsage, oracle.jbo.domain.Number keyValue);

    void clearDeepLinkViewCriteria(String viewObjectUsage, Boolean requeryIfFound);

    void clearViewCriteria(String viewObjectUsage, String vcName);

    void advancedSearch(String viewObjectUsage, ArrayList arguments, Boolean allConditionsMet);

}

