package OPERATIONPROJECT.model.BC.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 25 02:47:52 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustomerLookupVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CustomerLookupVOImpl() {
    }
}

