package OPERATIONPROJECT.model.BC.VO.Lookups;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 27 18:36:11 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PaymentStatusVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Rownumber,
        StatusId,
        StatusName;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return OPERATIONPROJECT.model
                                   .BC
                                   .VO
                                   .Lookups
                                   .PaymentStatusVORowImpl
                                   .AttributesEnum
                                   .firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return OPERATIONPROJECT.model
                                   .BC
                                   .VO
                                   .Lookups
                                   .PaymentStatusVORowImpl
                                   .AttributesEnum
                                   .firstIndex() + OPERATIONPROJECT.model
                                                                   .BC
                                                                   .VO
                                                                   .Lookups
                                                                   .PaymentStatusVORowImpl
                                                                   .AttributesEnum
                                                                   .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = OPERATIONPROJECT.model
                                       .BC
                                       .VO
                                       .Lookups
                                       .PaymentStatusVORowImpl
                                       .AttributesEnum
                                       .values();
            }
            return vals;
        }
    }
    public static final int ROWNUMBER = AttributesEnum.Rownumber.index();
    public static final int STATUSID = AttributesEnum.StatusId.index();
    public static final int STATUSNAME = AttributesEnum.StatusName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PaymentStatusVORowImpl() {
    }
}

