package OPERATIONPROJECT.model.BC.VO.Lookups;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 20 17:39:13 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PilotsVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Userid,
        FullNameEn,
        DriverUserName,
        UsergroupId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int USERID = AttributesEnum.Userid.index();
    public static final int FULLNAMEEN = AttributesEnum.FullNameEn.index();
    public static final int DRIVERUSERNAME = AttributesEnum.DriverUserName.index();
    public static final int USERGROUPID = AttributesEnum.UsergroupId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PilotsVORowImpl() {
    }
}

