package OPERATIONPROJECT.model.BC.VO.Lookups;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 01 04:53:44 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ResceduleDeliveryROVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ResceduleDeliveryROVImpl() {
    }
}

