package OPERATIONPROJECT.model.BC.VO;

import oracle.adf.share.ADFContext;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 18 04:51:16 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AgentAreasVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AgentAreasVOImpl() {
    }

    @Override
    public void prepareRowSetForQuery(ViewRowSetImpl viewRowSetImpl) {
        // TODO Implement this method
        viewRowSetImpl.ensureVariableManager().setVariableValue("bindAgent", ADFContext.getCurrent().getSecurityContext().getUserName());
        super.prepareRowSetForQuery(viewRowSetImpl);
    }


    /**
     * Returns the bind variable value for bindAgent.
     * @return bind variable value for bindAgent
     */
    public String getbindAgent() {
        return (String) getNamedWhereClauseParam("bindAgent");
    }

    /**
     * Sets <code>value</code> for bind variable bindAgent.
     * @param value value to bind as bindAgent
     */
    public void setbindAgent(String value) {
        setNamedWhereClauseParam("bindAgent", value);
    }
}

