package OPERATIONPROJECT.model.BC.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 22 13:30:22 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AreaContractInformationVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AreaContractInformationVOImpl() {
    }
}

