package OPERATIONPROJECT.model.BC.VO;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 25 20:59:17 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AreaContractVORowImpl extends ViewRowImpl {


    public static final int ENTITY_AREACONTRACTEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CardNo,
        ContractClientName,
        AreaId,
        NextDeliveryDate,
        LastChangedDate,
        ExpectedDeliveryDate,
        PNum,
        DefaultPriority,
        PerfectIssue,
        BOver,
        Lost,
        ZeroB,
        NeedCall,
        Priority8,
        Priority9,
        Priority10,
        Dispatchable,
        ContractPhone,
        ContractPhone2,
        ContractMobile,
        ContractMobile2,
        FuNote,
        Priority,
        WorkDate,
        CloseCode,
        CityName,
        RegionName,
        AreaName,
        StreetName,
        Address,
        HomeNo,
        FloorNo,
        FlatNo,
        CoverDate,
        Duration,
        HaveTickets,
        Perfectcheck,
        Issuecheck,
        Bovercheck,
        Lostcheck,
        Haveticketscheck,
        MustCall,
        CloseCodeName,
        selectTrans,
        TotalProductPrice,
        AreaContractInformation,
        Assignment,
        PromosDelivery,
        ViewOpenTicket,
        ContractDeliverySchedule,
        Assignment1,
        ArchiveDelivery,
        AreaContractVO_AgentAreasVOLookup,
        YesOrNoSLV,
        CloseCodeROV,
        YesNolkupVO1,
        AllCloseCodesVO1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CARDNO = AttributesEnum.CardNo.index();
    public static final int CONTRACTCLIENTNAME = AttributesEnum.ContractClientName.index();
    public static final int AREAID = AttributesEnum.AreaId.index();
    public static final int NEXTDELIVERYDATE = AttributesEnum.NextDeliveryDate.index();
    public static final int LASTCHANGEDDATE = AttributesEnum.LastChangedDate.index();
    public static final int EXPECTEDDELIVERYDATE = AttributesEnum.ExpectedDeliveryDate.index();
    public static final int PNUM = AttributesEnum.PNum.index();
    public static final int DEFAULTPRIORITY = AttributesEnum.DefaultPriority.index();
    public static final int PERFECTISSUE = AttributesEnum.PerfectIssue.index();
    public static final int BOVER = AttributesEnum.BOver.index();
    public static final int LOST = AttributesEnum.Lost.index();
    public static final int ZEROB = AttributesEnum.ZeroB.index();
    public static final int NEEDCALL = AttributesEnum.NeedCall.index();
    public static final int PRIORITY8 = AttributesEnum.Priority8.index();
    public static final int PRIORITY9 = AttributesEnum.Priority9.index();
    public static final int PRIORITY10 = AttributesEnum.Priority10.index();
    public static final int DISPATCHABLE = AttributesEnum.Dispatchable.index();
    public static final int CONTRACTPHONE = AttributesEnum.ContractPhone.index();
    public static final int CONTRACTPHONE2 = AttributesEnum.ContractPhone2.index();
    public static final int CONTRACTMOBILE = AttributesEnum.ContractMobile.index();
    public static final int CONTRACTMOBILE2 = AttributesEnum.ContractMobile2.index();
    public static final int FUNOTE = AttributesEnum.FuNote.index();
    public static final int PRIORITY = AttributesEnum.Priority.index();
    public static final int WORKDATE = AttributesEnum.WorkDate.index();
    public static final int CLOSECODE = AttributesEnum.CloseCode.index();
    public static final int CITYNAME = AttributesEnum.CityName.index();
    public static final int REGIONNAME = AttributesEnum.RegionName.index();
    public static final int AREANAME = AttributesEnum.AreaName.index();
    public static final int STREETNAME = AttributesEnum.StreetName.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int HOMENO = AttributesEnum.HomeNo.index();
    public static final int FLOORNO = AttributesEnum.FloorNo.index();
    public static final int FLATNO = AttributesEnum.FlatNo.index();
    public static final int COVERDATE = AttributesEnum.CoverDate.index();
    public static final int DURATION = AttributesEnum.Duration.index();
    public static final int HAVETICKETS = AttributesEnum.HaveTickets.index();
    public static final int PERFECTCHECK = AttributesEnum.Perfectcheck.index();
    public static final int ISSUECHECK = AttributesEnum.Issuecheck.index();
    public static final int BOVERCHECK = AttributesEnum.Bovercheck.index();
    public static final int LOSTCHECK = AttributesEnum.Lostcheck.index();
    public static final int HAVETICKETSCHECK = AttributesEnum.Haveticketscheck.index();
    public static final int MUSTCALL = AttributesEnum.MustCall.index();
    public static final int CLOSECODENAME = AttributesEnum.CloseCodeName.index();
    public static final int SELECTTRANS = AttributesEnum.selectTrans.index();
    public static final int TOTALPRODUCTPRICE = AttributesEnum.TotalProductPrice.index();
    public static final int AREACONTRACTINFORMATION = AttributesEnum.AreaContractInformation.index();
    public static final int ASSIGNMENT = AttributesEnum.Assignment.index();
    public static final int PROMOSDELIVERY = AttributesEnum.PromosDelivery.index();
    public static final int VIEWOPENTICKET = AttributesEnum.ViewOpenTicket.index();
    public static final int CONTRACTDELIVERYSCHEDULE = AttributesEnum.ContractDeliverySchedule.index();
    public static final int ASSIGNMENT1 = AttributesEnum.Assignment1.index();
    public static final int ARCHIVEDELIVERY = AttributesEnum.ArchiveDelivery.index();
    public static final int AREACONTRACTVO_AGENTAREASVOLOOKUP =
        AttributesEnum.AreaContractVO_AgentAreasVOLookup.index();
    public static final int YESORNOSLV = AttributesEnum.YesOrNoSLV.index();
    public static final int CLOSECODEROV = AttributesEnum.CloseCodeROV.index();
    public static final int YESNOLKUPVO1 = AttributesEnum.YesNolkupVO1.index();
    public static final int ALLCLOSECODESVO1 = AttributesEnum.AllCloseCodesVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AreaContractVORowImpl() {
    }

    /**
     * Gets AreaContractEO entity object.
     * @return the AreaContractEO
     */
    public EntityImpl getAreaContractEO() {
        return (EntityImpl) getEntity(ENTITY_AREACONTRACTEO);
    }

    /**
     * Gets the attribute value for CARD_NO using the alias name CardNo.
     * @return the CARD_NO
     */
    public Long getCardNo() {
        return (Long) getAttributeInternal(CARDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CARD_NO using the alias name CardNo.
     * @param value value to set the CARD_NO
     */
    public void setCardNo(Long value) {
        setAttributeInternal(CARDNO, value);
    }

    /**
     * Gets the attribute value for CONTRACT_CLIENT_NAME using the alias name ContractClientName.
     * @return the CONTRACT_CLIENT_NAME
     */
    public String getContractClientName() {
        return (String) getAttributeInternal(CONTRACTCLIENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_CLIENT_NAME using the alias name ContractClientName.
     * @param value value to set the CONTRACT_CLIENT_NAME
     */
    public void setContractClientName(String value) {
        setAttributeInternal(CONTRACTCLIENTNAME, value);
    }

    /**
     * Gets the attribute value for AREA_ID using the alias name AreaId.
     * @return the AREA_ID
     */
    public Long getAreaId() {
        return (Long) getAttributeInternal(AREAID);
    }

    /**
     * Sets <code>value</code> as attribute value for AREA_ID using the alias name AreaId.
     * @param value value to set the AREA_ID
     */
    public void setAreaId(Long value) {
        setAttributeInternal(AREAID, value);
    }

    /**
     * Gets the attribute value for NEXT_DELIVERY_DATE using the alias name NextDeliveryDate.
     * @return the NEXT_DELIVERY_DATE
     */
    public Date getNextDeliveryDate() {
        return (Date) getAttributeInternal(NEXTDELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for NEXT_DELIVERY_DATE using the alias name NextDeliveryDate.
     * @param value value to set the NEXT_DELIVERY_DATE
     */
    public void setNextDeliveryDate(Date value) {
        setAttributeInternal(NEXTDELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for LAST_CHANGED_DATE using the alias name LastChangedDate.
     * @return the LAST_CHANGED_DATE
     */
    public Date getLastChangedDate() {
        return (Date) getAttributeInternal(LASTCHANGEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_CHANGED_DATE using the alias name LastChangedDate.
     * @param value value to set the LAST_CHANGED_DATE
     */
    public void setLastChangedDate(Date value) {
        setAttributeInternal(LASTCHANGEDDATE, value);
    }

    /**
     * Gets the attribute value for EXPECTED_DELIVERY_DATE using the alias name ExpectedDeliveryDate.
     * @return the EXPECTED_DELIVERY_DATE
     */
    public Date getExpectedDeliveryDate() {
        return (Date) getAttributeInternal(EXPECTEDDELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPECTED_DELIVERY_DATE using the alias name ExpectedDeliveryDate.
     * @param value value to set the EXPECTED_DELIVERY_DATE
     */
    public void setExpectedDeliveryDate(Date value) {
        setAttributeInternal(EXPECTEDDELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for P_NUM using the alias name PNum.
     * @return the P_NUM
     */
    public Long getPNum() {
        return (Long) getAttributeInternal(PNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for P_NUM using the alias name PNum.
     * @param value value to set the P_NUM
     */
    public void setPNum(Long value) {
        setAttributeInternal(PNUM, value);
    }

    /**
     * Gets the attribute value for DEFAULT_PRIORITY using the alias name DefaultPriority.
     * @return the DEFAULT_PRIORITY
     */
    public Long getDefaultPriority() {
        return (Long) getAttributeInternal(DEFAULTPRIORITY);
    }

    /**
     * Sets <code>value</code> as attribute value for DEFAULT_PRIORITY using the alias name DefaultPriority.
     * @param value value to set the DEFAULT_PRIORITY
     */
    public void setDefaultPriority(Long value) {
        setAttributeInternal(DEFAULTPRIORITY, value);
    }

    /**
     * Gets the attribute value for PERFECT_ISSUE using the alias name PerfectIssue.
     * @return the PERFECT_ISSUE
     */
    public Long getPerfectIssue() {
        return (Long) getAttributeInternal(PERFECTISSUE);
    }

    /**
     * Sets <code>value</code> as attribute value for PERFECT_ISSUE using the alias name PerfectIssue.
     * @param value value to set the PERFECT_ISSUE
     */
    public void setPerfectIssue(Long value) {
        setAttributeInternal(PERFECTISSUE, value);
    }

    /**
     * Gets the attribute value for B_OVER using the alias name BOver.
     * @return the B_OVER
     */
    public Long getBOver() {
        return (Long) getAttributeInternal(BOVER);
    }

    /**
     * Sets <code>value</code> as attribute value for B_OVER using the alias name BOver.
     * @param value value to set the B_OVER
     */
    public void setBOver(Long value) {
        setAttributeInternal(BOVER, value);
    }

    /**
     * Gets the attribute value for LOST using the alias name Lost.
     * @return the LOST
     */
    public Long getLost() {
        return (Long) getAttributeInternal(LOST);
    }

    /**
     * Sets <code>value</code> as attribute value for LOST using the alias name Lost.
     * @param value value to set the LOST
     */
    public void setLost(Long value) {
        setAttributeInternal(LOST, value);
    }

    /**
     * Gets the attribute value for ZERO_B using the alias name ZeroB.
     * @return the ZERO_B
     */
    public Long getZeroB() {
        return (Long) getAttributeInternal(ZEROB);
    }

    /**
     * Sets <code>value</code> as attribute value for ZERO_B using the alias name ZeroB.
     * @param value value to set the ZERO_B
     */
    public void setZeroB(Long value) {
        setAttributeInternal(ZEROB, value);
    }

    /**
     * Gets the attribute value for NEED_CALL using the alias name NeedCall.
     * @return the NEED_CALL
     */
    public Long getNeedCall() {
        return (Long) getAttributeInternal(NEEDCALL);
    }

    /**
     * Sets <code>value</code> as attribute value for NEED_CALL using the alias name NeedCall.
     * @param value value to set the NEED_CALL
     */
    public void setNeedCall(Long value) {
        setAttributeInternal(NEEDCALL, value);
    }

    /**
     * Gets the attribute value for PRIORITY_8 using the alias name Priority8.
     * @return the PRIORITY_8
     */
    public Long getPriority8() {
        return (Long) getAttributeInternal(PRIORITY8);
    }

    /**
     * Sets <code>value</code> as attribute value for PRIORITY_8 using the alias name Priority8.
     * @param value value to set the PRIORITY_8
     */
    public void setPriority8(Long value) {
        setAttributeInternal(PRIORITY8, value);
    }

    /**
     * Gets the attribute value for PRIORITY_9 using the alias name Priority9.
     * @return the PRIORITY_9
     */
    public Long getPriority9() {
        return (Long) getAttributeInternal(PRIORITY9);
    }

    /**
     * Sets <code>value</code> as attribute value for PRIORITY_9 using the alias name Priority9.
     * @param value value to set the PRIORITY_9
     */
    public void setPriority9(Long value) {
        setAttributeInternal(PRIORITY9, value);
    }

    /**
     * Gets the attribute value for PRIORITY_10 using the alias name Priority10.
     * @return the PRIORITY_10
     */
    public Long getPriority10() {
        return (Long) getAttributeInternal(PRIORITY10);
    }

    /**
     * Sets <code>value</code> as attribute value for PRIORITY_10 using the alias name Priority10.
     * @param value value to set the PRIORITY_10
     */
    public void setPriority10(Long value) {
        setAttributeInternal(PRIORITY10, value);
    }

    /**
     * Gets the attribute value for DISPATCHABLE using the alias name Dispatchable.
     * @return the DISPATCHABLE
     */
    public Long getDispatchable() {
        return (Long) getAttributeInternal(DISPATCHABLE);
    }

    /**
     * Sets <code>value</code> as attribute value for DISPATCHABLE using the alias name Dispatchable.
     * @param value value to set the DISPATCHABLE
     */
    public void setDispatchable(Long value) {
        setAttributeInternal(DISPATCHABLE, value);
    }

    /**
     * Gets the attribute value for CONTRACT_PHONE using the alias name ContractPhone.
     * @return the CONTRACT_PHONE
     */
    public String getContractPhone() {
        return (String) getAttributeInternal(CONTRACTPHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_PHONE using the alias name ContractPhone.
     * @param value value to set the CONTRACT_PHONE
     */
    public void setContractPhone(String value) {
        setAttributeInternal(CONTRACTPHONE, value);
    }

    /**
     * Gets the attribute value for CONTRACT_PHONE2 using the alias name ContractPhone2.
     * @return the CONTRACT_PHONE2
     */
    public String getContractPhone2() {
        return (String) getAttributeInternal(CONTRACTPHONE2);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_PHONE2 using the alias name ContractPhone2.
     * @param value value to set the CONTRACT_PHONE2
     */
    public void setContractPhone2(String value) {
        setAttributeInternal(CONTRACTPHONE2, value);
    }

    /**
     * Gets the attribute value for CONTRACT_MOBILE using the alias name ContractMobile.
     * @return the CONTRACT_MOBILE
     */
    public String getContractMobile() {
        return (String) getAttributeInternal(CONTRACTMOBILE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_MOBILE using the alias name ContractMobile.
     * @param value value to set the CONTRACT_MOBILE
     */
    public void setContractMobile(String value) {
        setAttributeInternal(CONTRACTMOBILE, value);
    }

    /**
     * Gets the attribute value for CONTRACT_MOBILE2 using the alias name ContractMobile2.
     * @return the CONTRACT_MOBILE2
     */
    public String getContractMobile2() {
        return (String) getAttributeInternal(CONTRACTMOBILE2);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_MOBILE2 using the alias name ContractMobile2.
     * @param value value to set the CONTRACT_MOBILE2
     */
    public void setContractMobile2(String value) {
        setAttributeInternal(CONTRACTMOBILE2, value);
    }

    /**
     * Gets the attribute value for FU_NOTE using the alias name FuNote.
     * @return the FU_NOTE
     */
    public String getFuNote() {
        return (String) getAttributeInternal(FUNOTE);
    }

    /**
     * Sets <code>value</code> as attribute value for FU_NOTE using the alias name FuNote.
     * @param value value to set the FU_NOTE
     */
    public void setFuNote(String value) {
        setAttributeInternal(FUNOTE, value);
    }

    /**
     * Gets the attribute value for PRIORITY using the alias name Priority.
     * @return the PRIORITY
     */
    public Long getPriority() {
        return (Long) getAttributeInternal(PRIORITY);
    }

    /**
     * Sets <code>value</code> as attribute value for PRIORITY using the alias name Priority.
     * @param value value to set the PRIORITY
     */
    public void setPriority(Long value) {
        setAttributeInternal(PRIORITY, value);
    }

    /**
     * Gets the attribute value for WORK_DATE using the alias name WorkDate.
     * @return the WORK_DATE
     */
    public Date getWorkDate() {
        return (Date) getAttributeInternal(WORKDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for WORK_DATE using the alias name WorkDate.
     * @param value value to set the WORK_DATE
     */
    public void setWorkDate(Date value) {
        setAttributeInternal(WORKDATE, value);
    }

    /**
     * Gets the attribute value for CLOSE_CODE using the alias name CloseCode.
     * @return the CLOSE_CODE
     */
    public Long getCloseCode() {
        return (Long) getAttributeInternal(CLOSECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CLOSE_CODE using the alias name CloseCode.
     * @param value value to set the CLOSE_CODE
     */
    public void setCloseCode(Long value) {
        setAttributeInternal(CLOSECODE, value);
    }

    /**
     * Gets the attribute value for CITY_NAME using the alias name CityName.
     * @return the CITY_NAME
     */
    public String getCityName() {
        return (String) getAttributeInternal(CITYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CITY_NAME using the alias name CityName.
     * @param value value to set the CITY_NAME
     */
    public void setCityName(String value) {
        setAttributeInternal(CITYNAME, value);
    }

    /**
     * Gets the attribute value for REGION_NAME using the alias name RegionName.
     * @return the REGION_NAME
     */
    public String getRegionName() {
        return (String) getAttributeInternal(REGIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for REGION_NAME using the alias name RegionName.
     * @param value value to set the REGION_NAME
     */
    public void setRegionName(String value) {
        setAttributeInternal(REGIONNAME, value);
    }

    /**
     * Gets the attribute value for AREA_NAME using the alias name AreaName.
     * @return the AREA_NAME
     */
    public String getAreaName() {
        return (String) getAttributeInternal(AREANAME);
    }

    /**
     * Sets <code>value</code> as attribute value for AREA_NAME using the alias name AreaName.
     * @param value value to set the AREA_NAME
     */
    public void setAreaName(String value) {
        setAttributeInternal(AREANAME, value);
    }

    /**
     * Gets the attribute value for STREET_NAME using the alias name StreetName.
     * @return the STREET_NAME
     */
    public String getStreetName() {
        return (String) getAttributeInternal(STREETNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for STREET_NAME using the alias name StreetName.
     * @param value value to set the STREET_NAME
     */
    public void setStreetName(String value) {
        setAttributeInternal(STREETNAME, value);
    }

    /**
     * Gets the attribute value for ADDRESS using the alias name Address.
     * @return the ADDRESS
     */
    public String getAddress() {
        return (String) getAttributeInternal(ADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS using the alias name Address.
     * @param value value to set the ADDRESS
     */
    public void setAddress(String value) {
        setAttributeInternal(ADDRESS, value);
    }

    /**
     * Gets the attribute value for HOME_NO using the alias name HomeNo.
     * @return the HOME_NO
     */
    public String getHomeNo() {
        return (String) getAttributeInternal(HOMENO);
    }

    /**
     * Sets <code>value</code> as attribute value for HOME_NO using the alias name HomeNo.
     * @param value value to set the HOME_NO
     */
    public void setHomeNo(String value) {
        setAttributeInternal(HOMENO, value);
    }

    /**
     * Gets the attribute value for FLOOR_NO using the alias name FloorNo.
     * @return the FLOOR_NO
     */
    public String getFloorNo() {
        return (String) getAttributeInternal(FLOORNO);
    }

    /**
     * Sets <code>value</code> as attribute value for FLOOR_NO using the alias name FloorNo.
     * @param value value to set the FLOOR_NO
     */
    public void setFloorNo(String value) {
        setAttributeInternal(FLOORNO, value);
    }

    /**
     * Gets the attribute value for FLAT_NO using the alias name FlatNo.
     * @return the FLAT_NO
     */
    public String getFlatNo() {
        return (String) getAttributeInternal(FLATNO);
    }

    /**
     * Sets <code>value</code> as attribute value for FLAT_NO using the alias name FlatNo.
     * @param value value to set the FLAT_NO
     */
    public void setFlatNo(String value) {
        setAttributeInternal(FLATNO, value);
    }

    /**
     * Gets the attribute value for COVER_DATE using the alias name CoverDate.
     * @return the COVER_DATE
     */
    public Date getCoverDate() {
        return (Date) getAttributeInternal(COVERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for COVER_DATE using the alias name CoverDate.
     * @param value value to set the COVER_DATE
     */
    public void setCoverDate(Date value) {
        setAttributeInternal(COVERDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute selectTrans.
     * @return the selectTrans
     */
    public Boolean getselectTrans() {
        return (Boolean) getAttributeInternal(SELECTTRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute selectTrans.
     * @param value value to set the  selectTrans
     */
    public void setselectTrans(Boolean value) {
        setAttributeInternal(SELECTTRANS, value);
    }


    /**
     * Gets the attribute value for the calculated attribute TotalProductPrice.
     * @return the TotalProductPrice
     */
    public Number getTotalProductPrice() {
        return (Number) getAttributeInternal(TOTALPRODUCTPRICE);
    }


    /**
     * Gets the attribute value for CLOSE_CODE_NAME using the alias name CloseCodeName.
     * @return the CLOSE_CODE_NAME
     */
    public String getCloseCodeName() {
        return (String) getAttributeInternal(CLOSECODENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CLOSE_CODE_NAME using the alias name CloseCodeName.
     * @param value value to set the CLOSE_CODE_NAME
     */
    public void setCloseCodeName(String value) {
        setAttributeInternal(CLOSECODENAME, value);
    }

    /**
     * Gets the attribute value for MUST_CALL using the alias name MustCall.
     * @return the MUST_CALL
     */
    public String getMustCall() {
        return (String) getAttributeInternal(MUSTCALL);
    }

    /**
     * Sets <code>value</code> as attribute value for MUST_CALL using the alias name MustCall.
     * @param value value to set the MUST_CALL
     */
    public void setMustCall(String value) {
        setAttributeInternal(MUSTCALL, value);
    }

    /**
     * Gets the attribute value for HAVE_TICKETS using the alias name HaveTickets.
     * @return the HAVE_TICKETS
     */
    public Long getHaveTickets() {
        return (Long) getAttributeInternal(HAVETICKETS);
    }

    /**
     * Sets <code>value</code> as attribute value for HAVE_TICKETS using the alias name HaveTickets.
     * @param value value to set the HAVE_TICKETS
     */
    public void setHaveTickets(Long value) {
        setAttributeInternal(HAVETICKETS, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Perfectcheck.
     * @return the Perfectcheck
     */
    public Boolean getPerfectcheck() {
        return (Boolean) getAttributeInternal(PERFECTCHECK);
    }

    /**
     * Gets the attribute value for the calculated attribute Issuecheck.
     * @return the Issuecheck
     */
    public Boolean getIssuecheck() {
        return (Boolean) getAttributeInternal(ISSUECHECK);
    }

    /**
     * Gets the attribute value for the calculated attribute Bovercheck.
     * @return the Bovercheck
     */
    public Boolean getBovercheck() {
        return (Boolean) getAttributeInternal(BOVERCHECK);
    }

    /**
     * Gets the attribute value for the calculated attribute Lostcheck.
     * @return the Lostcheck
     */
    public Boolean getLostcheck() {
        return (Boolean) getAttributeInternal(LOSTCHECK);
    }

    /**
     * Gets the attribute value for the calculated attribute Haveticketscheck.
     * @return the Haveticketscheck
     */
    public Boolean getHaveticketscheck() {
        return (Boolean) getAttributeInternal(HAVETICKETSCHECK);
    }

    /**
     * Gets the attribute value for DURATION using the alias name Duration.
     * @return the DURATION
     */
    public String getDuration() {
        return (String) getAttributeInternal(DURATION);
    }

    /**
     * Sets <code>value</code> as attribute value for DURATION using the alias name Duration.
     * @param value value to set the DURATION
     */
    public void setDuration(String value) {
        setAttributeInternal(DURATION, value);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AreaContractInformation.
     */
    public RowIterator getAreaContractInformation() {
        return (RowIterator) getAttributeInternal(AREACONTRACTINFORMATION);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Assignment.
     */
    public RowIterator getAssignment() {
        return (RowIterator) getAttributeInternal(ASSIGNMENT);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PromosDelivery.
     */
    public RowIterator getPromosDelivery() {
        return (RowIterator) getAttributeInternal(PROMOSDELIVERY);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ViewOpenTicket.
     */
    public RowIterator getViewOpenTicket() {
        return (RowIterator) getAttributeInternal(VIEWOPENTICKET);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ContractDeliverySchedule.
     */
    public RowIterator getContractDeliverySchedule() {
        return (RowIterator) getAttributeInternal(CONTRACTDELIVERYSCHEDULE);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Assignment1.
     */
    public RowIterator getAssignment1() {
        return (RowIterator) getAttributeInternal(ASSIGNMENT1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ArchiveDelivery.
     */
    public RowIterator getArchiveDelivery() {
        return (RowIterator) getAttributeInternal(ARCHIVEDELIVERY);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AreaContractVO_AgentAreasVOLookup.
     */
    public RowSet getAreaContractVO_AgentAreasVOLookup() {
        return (RowSet) getAttributeInternal(AREACONTRACTVO_AGENTAREASVOLOOKUP);
    }

    /**
     * Gets the view accessor <code>RowSet</code> YesOrNoSLV.
     */
    public RowSet getYesOrNoSLV() {
        return (RowSet) getAttributeInternal(YESORNOSLV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CloseCodeROV.
     */
    public RowSet getCloseCodeROV() {
        return (RowSet) getAttributeInternal(CLOSECODEROV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> YesNolkupVO1.
     */
    public RowSet getYesNolkupVO1() {
        return (RowSet) getAttributeInternal(YESNOLKUPVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AllCloseCodesVO1.
     */
    public RowSet getAllCloseCodesVO1() {
        return (RowSet) getAttributeInternal(ALLCLOSECODESVO1);
    }
}

