package OPERATIONPROJECT.model.BC.VO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 25 14:02:49 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceScheduleVORowImpl extends ViewRowImpl {


    public static final int ENTITY_INVOICESCHEDULEEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AreaId,
        AreaName,
        ContractNum,
        WorkingDate,
        AccountingAgent,
        Track,
        AccountingAgentVO1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int AREAID = AttributesEnum.AreaId.index();
    public static final int AREANAME = AttributesEnum.AreaName.index();
    public static final int CONTRACTNUM = AttributesEnum.ContractNum.index();
    public static final int WORKINGDATE = AttributesEnum.WorkingDate.index();
    public static final int ACCOUNTINGAGENT = AttributesEnum.AccountingAgent.index();
    public static final int TRACK = AttributesEnum.Track.index();
    public static final int ACCOUNTINGAGENTVO1 = AttributesEnum.AccountingAgentVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InvoiceScheduleVORowImpl() {
    }
}

