package OPERATIONPROJECT.model.BC.VO;

import oracle.adf.share.ADFContext;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 26 12:29:39 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceScheduleAccountVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public InvoiceScheduleAccountVOImpl() {
    }

    /**
     * Returns the bind variable value for BLoggedUser.
     * @return bind variable value for BLoggedUser
     */
    public String getBLoggedUser() {
        return (String) getNamedWhereClauseParam("BLoggedUser");
    }

    /**
     * Sets <code>value</code> for bind variable BLoggedUser.
     * @param value value to bind as BLoggedUser
     */
    public void setBLoggedUser(String value) {
        setNamedWhereClauseParam("BLoggedUser", value);
    }
    @Override
    public void prepareRowSetForQuery(ViewRowSetImpl viewRowSetImpl) {
        viewRowSetImpl.ensureVariableManager().setVariableValue("BLoggedUser", ADFContext.getCurrent().getSecurityContext().getUserName());
        super.prepareRowSetForQuery(viewRowSetImpl);
    }
}

