package OPERATIONPROJECT.model.BC.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 25 14:02:51 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceScheduleVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public InvoiceScheduleVOImpl() {
    }
}

