package OPERATIONPROJECT.model.BC.VO;

import OPERATIONPROJECT.model.BC.EO.ProductContractDeliveryViewEOImpl;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 26 00:27:41 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductContractDeliveryVORowImpl extends ViewRowImpl {


    public static final int ENTITY_PRODUCTCONTRACTDELIVERYVIEWEO = 0;
    public static final int ENTITY_PRODUCTCONTRACTDELIVERYEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        CardNo,
        PackageVersion,
        PackageNo,
        ProductSku,
        Quantity,
        Price,
        AssignmentId,
        ConfQuant,
        ProductId,
        TreatmentId,
        QuantityConfirmed,
        ProductConId,
        DeliveryFlag1,
        ProductName,
        TreatmentName,
        NextDeliveryDate,
        PackageId,
        PartialSubmit,
        NewPackFlag,
        Financial,
        Assignment,
        ProductContractDeliveryVO_AreaContractVOLookup,
        ProductContractDeliveryVO_AssignmentVOLookup,
        TreatmentTypesROV,
        ProductsAndPackagesROV,
        ProductsAndPackagesROV1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int CARDNO = AttributesEnum.CardNo.index();
    public static final int PACKAGEVERSION = AttributesEnum.PackageVersion.index();
    public static final int PACKAGENO = AttributesEnum.PackageNo.index();
    public static final int PRODUCTSKU = AttributesEnum.ProductSku.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int PRICE = AttributesEnum.Price.index();
    public static final int ASSIGNMENTID = AttributesEnum.AssignmentId.index();
    public static final int CONFQUANT = AttributesEnum.ConfQuant.index();
    public static final int PRODUCTID = AttributesEnum.ProductId.index();
    public static final int TREATMENTID = AttributesEnum.TreatmentId.index();
    public static final int QUANTITYCONFIRMED = AttributesEnum.QuantityConfirmed.index();
    public static final int PRODUCTCONID = AttributesEnum.ProductConId.index();
    public static final int DELIVERYFLAG1 = AttributesEnum.DeliveryFlag1.index();
    public static final int PRODUCTNAME = AttributesEnum.ProductName.index();
    public static final int TREATMENTNAME = AttributesEnum.TreatmentName.index();
    public static final int NEXTDELIVERYDATE = AttributesEnum.NextDeliveryDate.index();
    public static final int PACKAGEID = AttributesEnum.PackageId.index();
    public static final int PARTIALSUBMIT = AttributesEnum.PartialSubmit.index();
    public static final int NEWPACKFLAG = AttributesEnum.NewPackFlag.index();
    public static final int FINANCIAL = AttributesEnum.Financial.index();
    public static final int ASSIGNMENT = AttributesEnum.Assignment.index();
    public static final int PRODUCTCONTRACTDELIVERYVO_AREACONTRACTVOLOOKUP =
        AttributesEnum.ProductContractDeliveryVO_AreaContractVOLookup.index();
    public static final int PRODUCTCONTRACTDELIVERYVO_ASSIGNMENTVOLOOKUP =
        AttributesEnum.ProductContractDeliveryVO_AssignmentVOLookup.index();
    public static final int TREATMENTTYPESROV = AttributesEnum.TreatmentTypesROV.index();
    public static final int PRODUCTSANDPACKAGESROV = AttributesEnum.ProductsAndPackagesROV.index();
    public static final int PRODUCTSANDPACKAGESROV1 = AttributesEnum.ProductsAndPackagesROV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProductContractDeliveryVORowImpl() {
    }


    /**
     * Gets ProductContractDeliveryEO entity object.
     * @return the ProductContractDeliveryEO
     */
    public EntityImpl getProductContractDeliveryEO() {
        return (EntityImpl) getEntity(ENTITY_PRODUCTCONTRACTDELIVERYEO);
    }


    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public DBSequence getId() {
        return (DBSequence) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for CARD_NO using the alias name CardNo.
     * @return the CARD_NO
     */
    public Long getCardNo() {
        return (Long) getAttributeInternal(CARDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CARD_NO using the alias name CardNo.
     * @param value value to set the CARD_NO
     */
    public void setCardNo(Long value) {
        setAttributeInternal(CARDNO, value);
    }


    /**
     * Gets the attribute value for PACKAGE_VERSION using the alias name PackageVersion.
     * @return the PACKAGE_VERSION
     */
    public Long getPackageVersion() {
        return (Long) getAttributeInternal(PACKAGEVERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for PACKAGE_VERSION using the alias name PackageVersion.
     * @param value value to set the PACKAGE_VERSION
     */
    public void setPackageVersion(Long value) {
        setAttributeInternal(PACKAGEVERSION, value);
    }

    /**
     * Gets the attribute value for PACKAGE_NO using the alias name PackageNo.
     * @return the PACKAGE_NO
     */
    public Long getPackageNo() {
        return (Long) getAttributeInternal(PACKAGENO);
    }

    /**
     * Sets <code>value</code> as attribute value for PACKAGE_NO using the alias name PackageNo.
     * @param value value to set the PACKAGE_NO
     */
    public void setPackageNo(Long value) {
        setAttributeInternal(PACKAGENO, value);
    }


    /**
     * Gets the attribute value for PRODUCT_SKU using the alias name ProductSku.
     * @return the PRODUCT_SKU
     */
    public String getProductSku() {
        return (String) getAttributeInternal(PRODUCTSKU);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_SKU using the alias name ProductSku.
     * @param value value to set the PRODUCT_SKU
     */
    public void setProductSku(String value) {
        setAttributeInternal(PRODUCTSKU, value);
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public Long getQuantity() {
        return (Long) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(Long value) {
        setAttributeInternal(QUANTITY, value);
    }


    /**
     * Gets the attribute value for PRICE using the alias name Price.
     * @return the PRICE
     */
    public Long getPrice() {
        return (Long) getAttributeInternal(PRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRICE using the alias name Price.
     * @param value value to set the PRICE
     */
    public void setPrice(Long value) {
        setAttributeInternal(PRICE, value);
    }


    /**
     * Gets the attribute value for ASSIGNMENT_ID using the alias name AssignmentId.
     * @return the ASSIGNMENT_ID
     */
    public Long getAssignmentId() {
        return (Long) getAttributeInternal(ASSIGNMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSIGNMENT_ID using the alias name AssignmentId.
     * @param value value to set the ASSIGNMENT_ID
     */
    public void setAssignmentId(Long value) {
        setAttributeInternal(ASSIGNMENTID, value);
    }


    /**
     * Gets the attribute value for the calculated attribute ConfQuant.
     * @return the ConfQuant
     */
    public Long getConfQuant() {
        return (Long) getAttributeInternal(CONFQUANT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ConfQuant.
     * @param value value to set the  ConfQuant
     */
    public void setConfQuant(Long value) {
        setAttributeInternal(CONFQUANT, value);
    }

    /**
     * Gets the attribute value for PRODUCT_ID using the alias name ProductId.
     * @return the PRODUCT_ID
     */
    public String getProductId() {
        return (String) getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_ID using the alias name ProductId.
     * @param value value to set the PRODUCT_ID
     */
    public void setProductId(String value) {
        setAttributeInternal(PRODUCTID, value);
     
        
    }

    /**
     * Gets the attribute value for TREATMENT_ID using the alias name TreatmentId.
     * @return the TREATMENT_ID
     */
    public Long getTreatmentId() {
        return (Long) getAttributeInternal(TREATMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for TREATMENT_ID using the alias name TreatmentId.
     * @param value value to set the TREATMENT_ID
     */
    public void setTreatmentId(Long value) {
        setAttributeInternal(TREATMENTID, value);
    }

    /**
     * Gets the attribute value for QUANTITY_CONFIRMED using the alias name QuantityConfirmed.
     * @return the QUANTITY_CONFIRMED
     */
    public Long getQuantityConfirmed() {
        return (Long) getAttributeInternal(QUANTITYCONFIRMED);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY_CONFIRMED using the alias name QuantityConfirmed.
     * @param value value to set the QUANTITY_CONFIRMED
     */
    public void setQuantityConfirmed(Long value) {
        setAttributeInternal(QUANTITYCONFIRMED, value);
    }

    /**
     * Gets the attribute value for PRODUCT_CON_ID using the alias name ProductConId.
     * @return the PRODUCT_CON_ID
     */
    public Long getProductConId() {
        return (Long) getAttributeInternal(PRODUCTCONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_CON_ID using the alias name ProductConId.
     * @param value value to set the PRODUCT_CON_ID
     */
    public void setProductConId(Long value) {
        setAttributeInternal(PRODUCTCONID, value);
    }

    /**
     * Gets the attribute value for DELIVERY_FLAG using the alias name DeliveryFlag.
     * @return the DELIVERY_FLAG
     */
    public Long getDeliveryFlag1() {
        return (Long) getAttributeInternal(DELIVERYFLAG1);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVERY_FLAG using the alias name DeliveryFlag.
     * @param value value to set the DELIVERY_FLAG
     */
    public void setDeliveryFlag1(Long value) {
        setAttributeInternal(DELIVERYFLAG1, value);
    }

    /**
     * Gets the attribute value for PRODUCT_NAME using the alias name ProductName.
     * @return the PRODUCT_NAME
     */
    public String getProductName() {
        return (String) getAttributeInternal(PRODUCTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_NAME using the alias name ProductName.
     * @param value value to set the PRODUCT_NAME
     */
    public void setProductName(String value) {
        setAttributeInternal(PRODUCTNAME, value);
    }

    /**
     * Gets the attribute value for TREATMENT_NAME using the alias name TreatmentName.
     * @return the TREATMENT_NAME
     */
    public String getTreatmentName() {
        return (String) getAttributeInternal(TREATMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TREATMENT_NAME using the alias name TreatmentName.
     * @param value value to set the TREATMENT_NAME
     */
    public void setTreatmentName(String value) {
        setAttributeInternal(TREATMENTNAME, value);
    }

    /**
     * Gets the attribute value for NEXT_DELIVERY_DATE using the alias name NextDeliveryDate.
     * @return the NEXT_DELIVERY_DATE
     */
    public Timestamp getNextDeliveryDate() {
        return (Timestamp) getAttributeInternal(NEXTDELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for NEXT_DELIVERY_DATE using the alias name NextDeliveryDate.
     * @param value value to set the NEXT_DELIVERY_DATE
     */
    public void setNextDeliveryDate(Timestamp value) {
        setAttributeInternal(NEXTDELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for PACKAGE_ID using the alias name PackageId.
     * @return the PACKAGE_ID
     */
    public String getPackageId() {
        return (String) getAttributeInternal(PACKAGEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PACKAGE_ID using the alias name PackageId.
     * @param value value to set the PACKAGE_ID
     */
    public void setPackageId(String value) {
        setAttributeInternal(PACKAGEID, value);
    }

    /**
     * Gets the attribute value for PARTIAL_SUBMIT using the alias name PartialSubmit.
     * @return the PARTIAL_SUBMIT
     */
    public Long getPartialSubmit() {
        return (Long) getAttributeInternal(PARTIALSUBMIT);
    }

    /**
     * Sets <code>value</code> as attribute value for PARTIAL_SUBMIT using the alias name PartialSubmit.
     * @param value value to set the PARTIAL_SUBMIT
     */
    public void setPartialSubmit(Long value) {
        setAttributeInternal(PARTIALSUBMIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NewPackFlag.
     * @return the NewPackFlag
     */
    public Long getNewPackFlag() {
        return (Long) getAttributeInternal(NEWPACKFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NewPackFlag.
     * @param value value to set the  NewPackFlag
     */
    public void setNewPackFlag(Long value) {
        setAttributeInternal(NEWPACKFLAG, value);
    }

    /**
     * Gets the attribute value for FINANCIAL using the alias name Financial.
     * @return the FINANCIAL
     */
    public Long getFinancial() {
        return (Long) getAttributeInternal(FINANCIAL);
    }

    /**
     * Sets <code>value</code> as attribute value for FINANCIAL using the alias name Financial.
     * @param value value to set the FINANCIAL
     */
    public void setFinancial(Long value) {
        setAttributeInternal(FINANCIAL, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Assignment.
     */
    public RowIterator getAssignment() {
        return (RowIterator) getAttributeInternal(ASSIGNMENT);
    }

    /**
     * Gets ProductContractDeliveryViewEO entity object.
     * @return the ProductContractDeliveryViewEO
     */
    public ProductContractDeliveryViewEOImpl getProductContractDeliveryViewEO() {
        return (ProductContractDeliveryViewEOImpl) getEntity(ENTITY_PRODUCTCONTRACTDELIVERYVIEWEO);
    }


    /**
     * Gets the view accessor <code>RowSet</code> ProductContractDeliveryVO_AreaContractVOLookup.
     */
    public RowSet getProductContractDeliveryVO_AreaContractVOLookup() {
        return (RowSet) getAttributeInternal(PRODUCTCONTRACTDELIVERYVO_AREACONTRACTVOLOOKUP);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductContractDeliveryVO_AssignmentVOLookup.
     */
    public RowSet getProductContractDeliveryVO_AssignmentVOLookup() {
        return (RowSet) getAttributeInternal(PRODUCTCONTRACTDELIVERYVO_ASSIGNMENTVOLOOKUP);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TreatmentTypesROV.
     */
    public RowSet getTreatmentTypesROV() {
        return (RowSet) getAttributeInternal(TREATMENTTYPESROV);
    }


    /**
     * Gets the view accessor <code>RowSet</code> ProductsAndPackagesROV.
     */
    public RowSet getProductsAndPackagesROV() {
        return (RowSet) getAttributeInternal(PRODUCTSANDPACKAGESROV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductsAndPackagesROV1.
     */
    public RowSet getProductsAndPackagesROV1() {
        return (RowSet) getAttributeInternal(PRODUCTSANDPACKAGESROV1);
    }


}

