package OPERATIONPROJECT.model.BC.VO;

import OPERATIONPROJECT.model.BC.EO.WeekDaysEOImpl;

import OPERATIONPROJECT.model.BC.VO.common.WeekDaysVORow;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 30 13:25:13 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WeekDaysVORowImpl extends ViewRowImpl implements WeekDaysVORow {


    public static final int ENTITY_WEEKDAYSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        WorkingDate,
        DayName,
        B_Num,
        SMSContent,
        SchedulingTable,
        OperationWork,
        AreaSms,
        TeamleaderDashboard,
        AgentAreas,
        AgentAreasSupervisor,
        SchedulingSummary,
        TeamLeaderAgentSummary,
        TeamLeaderDaySummary,
        TeamLeaderPriority,
        TeamLeaderNeedCall,
        SupervisorAreaSummary,
        TeamLeaderTotals,
        SupervisorAreasDetails,
        SupervisorAreaMaster,
        InvoiceSchedule,
        InvoiceScheduleAccount;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int WORKINGDATE = AttributesEnum.WorkingDate.index();
    public static final int DAYNAME = AttributesEnum.DayName.index();
    public static final int B_NUM = AttributesEnum.B_Num.index();
    public static final int SMSCONTENT = AttributesEnum.SMSContent.index();
    public static final int SCHEDULINGTABLE = AttributesEnum.SchedulingTable.index();
    public static final int OPERATIONWORK = AttributesEnum.OperationWork.index();
    public static final int AREASMS = AttributesEnum.AreaSms.index();
    public static final int TEAMLEADERDASHBOARD = AttributesEnum.TeamleaderDashboard.index();
    public static final int AGENTAREAS = AttributesEnum.AgentAreas.index();
    public static final int AGENTAREASSUPERVISOR = AttributesEnum.AgentAreasSupervisor.index();
    public static final int SCHEDULINGSUMMARY = AttributesEnum.SchedulingSummary.index();
    public static final int TEAMLEADERAGENTSUMMARY = AttributesEnum.TeamLeaderAgentSummary.index();
    public static final int TEAMLEADERDAYSUMMARY = AttributesEnum.TeamLeaderDaySummary.index();
    public static final int TEAMLEADERPRIORITY = AttributesEnum.TeamLeaderPriority.index();
    public static final int TEAMLEADERNEEDCALL = AttributesEnum.TeamLeaderNeedCall.index();
    public static final int SUPERVISORAREASUMMARY = AttributesEnum.SupervisorAreaSummary.index();
    public static final int TEAMLEADERTOTALS = AttributesEnum.TeamLeaderTotals.index();
    public static final int SUPERVISORAREASDETAILS = AttributesEnum.SupervisorAreasDetails.index();
    public static final int SUPERVISORAREAMASTER = AttributesEnum.SupervisorAreaMaster.index();
    public static final int INVOICESCHEDULE = AttributesEnum.InvoiceSchedule.index();
    public static final int INVOICESCHEDULEACCOUNT = AttributesEnum.InvoiceScheduleAccount.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WeekDaysVORowImpl() {
        /*DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");  
           LocalDateTime now = LocalDateTime.now();  
           System.out.println(dtf.format(now)); 
        System.err.println("Current Date"+dtf.format(now));
        this.setWorkingDate(Date.toDate(dtf.format(now)));*/
       // System.err.println("Current Row Date"+this.getWorkingDate());
       // setAttributeInternal(WORKINGDATE, (Date)Date.getCurrentDate() );

    }

    /**
     * Gets WeekDaysEO entity object.
     * @return the WeekDaysEO
     */
    public WeekDaysEOImpl getWeekDaysEO() {
        return (WeekDaysEOImpl) getEntity(ENTITY_WEEKDAYSEO);
    }

    /**
     * Gets the attribute value for WORKING_DATE using the alias name WorkingDate.
     * @return the WORKING_DATE
     */
    public Date getWorkingDate() {
       // return (Date)Date.getCurrentDate() ;
        return (Date) getAttributeInternal(WORKINGDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for WORKING_DATE using the alias name WorkingDate.
     * @param value value to set the WORKING_DATE
     */
    public void setWorkingDate(Date value) {
        setAttributeInternal(WORKINGDATE, value);
    }

    /**
     * Gets the attribute value for DAY_NAME using the alias name DayName.
     * @return the DAY_NAME
     */
    public String getDayName() {
        return (String) getAttributeInternal(DAYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DAY_NAME using the alias name DayName.
     * @param value value to set the DAY_NAME
     */
    public void setDayName(String value) {
        setAttributeInternal(DAYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute B_Num.
     * @return the B_Num
     */
    public Long getB_Num() {
        return (Long) getAttributeInternal(B_NUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute B_Num.
     * @param value value to set the  B_Num
     */
    public void setB_Num(Long value) {
        setAttributeInternal(B_NUM, value);
    }
    /**
     * Gets the attribute value for the calculated attribute SMSContent.
     * @return the SMSContent
     */
    public String getSMSContent() {
        return (String) getAttributeInternal(SMSCONTENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SMSContent.
     * @param value value to set the  SMSContent
     */
    public void setSMSContent(String value) {
        setAttributeInternal(SMSCONTENT, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SchedulingTable.
     */
    public RowIterator getSchedulingTable() {
        return (RowIterator) getAttributeInternal(SCHEDULINGTABLE);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OperationWork.
     */
    public RowIterator getOperationWork() {
        return (RowIterator) getAttributeInternal(OPERATIONWORK);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AreaSms.
     */
    public RowIterator getAreaSms() {
        return (RowIterator) getAttributeInternal(AREASMS);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TeamleaderDashboard.
     */
    public RowIterator getTeamleaderDashboard() {
        return (RowIterator) getAttributeInternal(TEAMLEADERDASHBOARD);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AgentAreas.
     */
    public RowIterator getAgentAreas() {
        return (RowIterator) getAttributeInternal(AGENTAREAS);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AgentAreasSupervisor.
     */
    public RowIterator getAgentAreasSupervisor() {
        return (RowIterator) getAttributeInternal(AGENTAREASSUPERVISOR);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SchedulingSummary.
     */
    public RowIterator getSchedulingSummary() {
        return (RowIterator) getAttributeInternal(SCHEDULINGSUMMARY);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TeamLeaderAgentSummary.
     */
    public RowIterator getTeamLeaderAgentSummary() {
        return (RowIterator) getAttributeInternal(TEAMLEADERAGENTSUMMARY);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TeamLeaderDaySummary.
     */
    public RowIterator getTeamLeaderDaySummary() {
        return (RowIterator) getAttributeInternal(TEAMLEADERDAYSUMMARY);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TeamLeaderPriority.
     */
    public RowIterator getTeamLeaderPriority() {
        return (RowIterator) getAttributeInternal(TEAMLEADERPRIORITY);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TeamLeaderNeedCall.
     */
    public RowIterator getTeamLeaderNeedCall() {
        return (RowIterator) getAttributeInternal(TEAMLEADERNEEDCALL);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SupervisorAreaSummary.
     */
    public RowIterator getSupervisorAreaSummary() {
        return (RowIterator) getAttributeInternal(SUPERVISORAREASUMMARY);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TeamLeaderTotals.
     */
    public RowIterator getTeamLeaderTotals() {
        return (RowIterator) getAttributeInternal(TEAMLEADERTOTALS);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SupervisorAreasDetails.
     */
    public RowIterator getSupervisorAreasDetails() {
        return (RowIterator) getAttributeInternal(SUPERVISORAREASDETAILS);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SupervisorAreaMaster.
     */
    public RowIterator getSupervisorAreaMaster() {
        return (RowIterator) getAttributeInternal(SUPERVISORAREAMASTER);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link InvoiceSchedule.
     */
    public RowIterator getInvoiceSchedule() {
        return (RowIterator) getAttributeInternal(INVOICESCHEDULE);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link InvoiceScheduleAccount.
     */
    public RowIterator getInvoiceScheduleAccount() {
        return (RowIterator) getAttributeInternal(INVOICESCHEDULEACCOUNT);
    }
}

