package OPERATIONPROJECT.model.BC.VO.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 19 12:43:20 EET 2020
// ---------------------------------------------------------------------
public interface PromosDeliveryVORow extends Row {
    void setProductSku(String value);
}

