package OPERATIONPROJECT.model.BC.VO.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 02 09:43:05 EET 2021
// ---------------------------------------------------------------------
public interface WeekDaysVORow extends Row {
    Date getWorkingDate();

    void setWorkingDate(Date value);

    String getDayName();

    void setDayName(String value);

    Long getB_Num();

    void setB_Num(Long value);

    String getSMSContent();

    void setSMSContent(String value);
}

