package OPERATIONPROJECT.model.BC.AM;

import OPERATIONPROJECT.model.BC.AM.common.AppModuleAM;


import OPERATIONPROJECT.model.BC.VO.AgentAreasVOImpl;

import OPERATIONPROJECT.model.BC.VO.AreaContractInformationVOImpl;
import OPERATIONPROJECT.model.BC.VO.InvoiceScheduleAccountVOImpl;
import OPERATIONPROJECT.model.BC.VO.InvoiceScheduleVOImpl;
import OPERATIONPROJECT.model.BC.VO.Lookups.PostponeDurationVOImpl;


import OPERATIONPROJECT.model.BC.VO.Lookups.ProductTreatsPriceVOImpl;
import OPERATIONPROJECT.model.BC.VO.Lookups.PromosLookupVOImpl;
import OPERATIONPROJECT.model.BC.VO.ProductContractDeliveryVOImpl;

import OPERATIONPROJECT.model.BC.VO.ProductContractVOImpl;
import OPERATIONPROJECT.model.BC.VO.PromosDeliveryVOImpl;
import OPERATIONPROJECT.model.BC.VO.WeekDaysVOImpl;

import oracle.jbo.server.ViewLinkImpl;


import oracle.jbo.server.ViewObjectImpl;

import oracle.jheadstart.model.adfbc.v2.JhsApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 25 19:29:10 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleAMImpl extends JhsApplicationModuleImpl implements AppModuleAM {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleAMImpl() {
    }

    /**
     * Container's getter for Countries1.
     * @return Countries1
     */
    public ViewObjectImpl getCountries1() {
        return (ViewObjectImpl) findViewObject("Countries1");
    }

    /**
     * Container's getter for WeekDaysVO.
     * @return WeekDaysVO
     */
    public WeekDaysVOImpl getWeekDaysVO() {
        return (WeekDaysVOImpl) findViewObject("WeekDaysVO");
    }

    /**
     * Container's getter for TeamleaderDashboardVO.
     * @return TeamleaderDashboardVO
     */
    public ViewObjectImpl getTeamleaderDashboardVO() {
        return (ViewObjectImpl) findViewObject("TeamleaderDashboardVO");
    }

    /**
     * Container's getter for AreaSmsVO.
     * @return AreaSmsVO
     */
    public ViewObjectImpl getAreaSmsVO() {
        return (ViewObjectImpl) findViewObject("AreaSmsVO");
    }

    /**
     * Container's getter for OperationWorkVO.
     * @return OperationWorkVO
     */
    public ViewObjectImpl getOperationWorkVO() {
        return (ViewObjectImpl) findViewObject("OperationWorkVO");
    }

    /**
     * Container's getter for SchedulingTableIncludeVO.
     * @return SchedulingTableIncludeVO
     */
    public ViewObjectImpl getSchedulingTableIncludeVO() {
        return (ViewObjectImpl) findViewObject("SchedulingTableIncludeVO");
    }

    /**
     * Container's getter for SchedulingTableExcludeVO.
     * @return SchedulingTableExcludeVO
     */
    public ViewObjectImpl getSchedulingTableExcludeVO() {
        return (ViewObjectImpl) findViewObject("SchedulingTableExcludeVO");
    }

    /**
     * Container's getter for WeekDaysAgentVO.
     * @return WeekDaysAgentVO
     */
    public WeekDaysVOImpl getWeekDaysAgentVO() {
        return (WeekDaysVOImpl) findViewObject("WeekDaysAgentVO");
    }

    /**
     * Container's getter for AgentAreasDetVO.
     * @return AgentAreasDetVO
     */
    public AgentAreasVOImpl getAgentAreasDetVO() {
        return (AgentAreasVOImpl) findViewObject("AgentAreasDetVO");
    }

    /**
     * Container's getter for AgentAreasVO.
     * @return AgentAreasVO
     */
    public AgentAreasVOImpl getAgentAreasVO() {
        return (AgentAreasVOImpl) findViewObject("AgentAreasVO");
    }

    /**
     * Container's getter for AreaContractVO.
     * @return AreaContractVO
     */
    public ViewObjectImpl getAreaContractVO() {
        return (ViewObjectImpl) findViewObject("AreaContractVO");
    }


    /**
     * Container's getter for AreaContractInformationVO.
     * @return AreaContractInformationVO
     */
    public AreaContractInformationVOImpl getAreaContractInformationVO() {
        return (AreaContractInformationVOImpl) findViewObject("AreaContractInformationVO");
    }


    /**
     * Container's getter for PromosDeliveryVO.
     * @return PromosDeliveryVO
     */
    public PromosDeliveryVOImpl getPromosDeliveryVO() {
        return (PromosDeliveryVOImpl) findViewObject("PromosDeliveryVO");
    }

    /**
     * Container's getter for WeekDaysTeamleaderDashboardVL.
     * @return WeekDaysTeamleaderDashboardVL
     */
    public ViewLinkImpl getWeekDaysTeamleaderDashboardVL() {
        return (ViewLinkImpl) findViewLink("WeekDaysTeamleaderDashboardVL");
    }

    /**
     * Container's getter for WeekDaysAreaSmsVL.
     * @return WeekDaysAreaSmsVL
     */
    public ViewLinkImpl getWeekDaysAreaSmsVL() {
        return (ViewLinkImpl) findViewLink("WeekDaysAreaSmsVL");
    }

    /**
     * Container's getter for WeekDaysOperationWorkVL.
     * @return WeekDaysOperationWorkVL
     */
    public ViewLinkImpl getWeekDaysOperationWorkVL() {
        return (ViewLinkImpl) findViewLink("WeekDaysOperationWorkVL");
    }

    /**
     * Container's getter for WeekDaysSchedulingTableIncludeVL.
     * @return WeekDaysSchedulingTableIncludeVL
     */
    public ViewLinkImpl getWeekDaysSchedulingTableIncludeVL() {
        return (ViewLinkImpl) findViewLink("WeekDaysSchedulingTableIncludeVL");
    }

    /**
     * Container's getter for WeekDaysSchedulingTableExcludeVL.
     * @return WeekDaysSchedulingTableExcludeVL
     */
    public ViewLinkImpl getWeekDaysSchedulingTableExcludeVL() {
        return (ViewLinkImpl) findViewLink("WeekDaysSchedulingTableExcludeVL");
    }

    /**
     * Container's getter for WeekDaysAgentAreasVL.
     * @return WeekDaysAgentAreasVL
     */
    public ViewLinkImpl getWeekDaysAgentAreasVL() {
        return (ViewLinkImpl) findViewLink("WeekDaysAgentAreasVL");
    }

    /**
     * Container's getter for AgentAreasAreaContractVL.
     * @return AgentAreasAreaContractVL
     */
    public ViewLinkImpl getAgentAreasAreaContractVL() {
        return (ViewLinkImpl) findViewLink("AgentAreasAreaContractVL");
    }


    /**
     * Container's getter for AreaContractContInfoVL.
     * @return AreaContractContInfoVL
     */
    public ViewLinkImpl getAreaContractContInfoVL() {
        return (ViewLinkImpl) findViewLink("AreaContractContInfoVL");
    }


    /**
     * Container's getter for AssignmentProductContDeliveryVL.
     * @return AssignmentProductContDeliveryVL
     */
    public ViewLinkImpl getAssignmentProductContDeliveryVL() {
        return (ViewLinkImpl) findViewLink("AssignmentProductContDeliveryVL");
    }

    /**
     * Container's getter for AreaContractPromosVL.
     * @return AreaContractPromosVL
     */
    public ViewLinkImpl getAreaContractPromosVL() {
        return (ViewLinkImpl) findViewLink("AreaContractPromosVL");
    }


    /**
     * Container's getter for ViewOpenTicketVO1.
     * @return ViewOpenTicketVO1
     */
    public ViewObjectImpl getViewOpenTicketVO() {
        return (ViewObjectImpl) findViewObject("ViewOpenTicketVO");
    }

    /**
     * Container's getter for AreaContractViewOpenTicketVL1.
     * @return AreaContractViewOpenTicketVL1
     */
    public ViewLinkImpl getAreaContractViewOpenTicketVL() {
        return (ViewLinkImpl) findViewLink("AreaContractViewOpenTicketVL");
    }

    /**
     * Container's getter for OpenTicketVO1.
     * @return OpenTicketVO1
     */
    public ViewObjectImpl getOpenTicketVO() {
        return (ViewObjectImpl) findViewObject("OpenTicketVO");
    }

    /**
     * Container's getter for WeekDaysVO1.
     * @return WeekDaysVO1
     */
    public WeekDaysVOImpl getWeekDaysSupervisorVO() {
        return (WeekDaysVOImpl) findViewObject("WeekDaysSupervisorVO");
    }


    /**
     * Container's getter for AgentAreasSupervisor1.
     * @return AgentAreasSupervisor1
     */
    public ViewObjectImpl getAgentAreasSupervisor() {
        return (ViewObjectImpl) findViewObject("AgentAreasSupervisor");
    }

    /**
     * Container's getter for WeekDaysAgentAreasSupervisorVL1.
     * @return WeekDaysAgentAreasSupervisorVL1
     */
    public ViewLinkImpl getWeekDaysAgentAreasSupervisorVL() {
        return (ViewLinkImpl) findViewLink("WeekDaysAgentAreasSupervisorVL");
    }


    /**
     * Container's getter for UsersDispatchROV1.
     * @return UsersDispatchROV1
     */
    public ViewObjectImpl getUsersROV() {
        return (ViewObjectImpl) findViewObject("UsersROV");
    }


    /**
     * Container's getter for SchedulingSummaryVO2.
     * @return SchedulingSummaryVO2
     */
    public ViewObjectImpl getSchedulingSummaryVO2() {
        return (ViewObjectImpl) findViewObject("SchedulingSummaryVO2");
    }

    /**
     * Container's getter for WeekDaysSchedulingSummaryVL2.
     * @return WeekDaysSchedulingSummaryVL2
     */
    public ViewLinkImpl getWeekDaysSchedulingSummaryVL2() {
        return (ViewLinkImpl) findViewLink("WeekDaysSchedulingSummaryVL2");
    }

    /**
     * Container's getter for DriversVO1.
     * @return DriversVO1
     */
    public ViewObjectImpl getDriversVO1() {
        return (ViewObjectImpl) findViewObject("DriversVO1");
    }

    /**
     * Container's getter for SpareVO1.
     * @return SpareVO1
     */
    public ViewObjectImpl getSpareVO1() {
        return (ViewObjectImpl) findViewObject("SpareVO1");
    }


    /**
     * Container's getter for AssignedDriversAreasVO1.
     * @return AssignedDriversAreasVO1
     */
    public ViewObjectImpl getAssignedDriversAreasVO1() {
        return (ViewObjectImpl) findViewObject("AssignedDriversAreasVO1");
    }

    /**
     * Container's getter for AssignedDriversAreasVO2.
     * @return AssignedDriversAreasVO2
     */
    public ViewObjectImpl getAssignedDriversAreasVO2() {
        return (ViewObjectImpl) findViewObject("AssignedDriversAreasVO2");
    }

    /**
     * Container's getter for Areas_AssignedDriversVL1.
     * @return Areas_AssignedDriversVL1
     */
    public ViewLinkImpl getAreas_AssignedDriversVL1() {
        return (ViewLinkImpl) findViewLink("Areas_AssignedDriversVL1");
    }

    /**
     * Container's getter for DriversStreetVO1.
     * @return DriversStreetVO1
     */
    public ViewObjectImpl getDriversStreetVO1() {
        return (ViewObjectImpl) findViewObject("DriversStreetVO1");
    }

    /**
     * Container's getter for DriversStreetSuperVisorAreasVL1.
     * @return DriversStreetSuperVisorAreasVL1
     */
    public ViewLinkImpl getDriversStreetSuperVisorAreasVL1() {
        return (ViewLinkImpl) findViewLink("DriversStreetSuperVisorAreasVL1");
    }

    /**
     * Container's getter for CityROV1.
     * @return CityROV1
     */
    public ViewObjectImpl getCityROV1() {
        return (ViewObjectImpl) findViewObject("CityROV1");
    }


    /**
     * Container's getter for AreaROV1.
     * @return AreaROV1
     */
    public ViewObjectImpl getAreaROV1() {
        return (ViewObjectImpl) findViewObject("AreaROV1");
    }

    /**
     * Container's getter for RegionROV1.
     * @return RegionROV1
     */
    public ViewObjectImpl getRegionROV1() {
        return (ViewObjectImpl) findViewObject("RegionROV1");
    }

    /**
     * Container's getter for AreaContractInformationVO1.
     * @return AreaContractInformationVO1
     */
    public AreaContractInformationVOImpl getAreaContractInformationVO1() {
        return (AreaContractInformationVOImpl) findViewObject("AreaContractInformationVO1");
    }

    /**
     * Container's getter for RegionROV2.
     * @return RegionROV2
     */
    public ViewObjectImpl getRegionROV2() {
        return (ViewObjectImpl) findViewObject("RegionROV2");
    }

    /**
     * Container's getter for CityRegionVL1.
     * @return CityRegionVL1
     */
    public ViewLinkImpl getCityRegionVL1() {
        return (ViewLinkImpl) findViewLink("CityRegionVL1");
    }


    /**
     * Container's getter for TeamLeaderDaySummaryVO2.
     * @return TeamLeaderDaySummaryVO2
     */
    public ViewObjectImpl getTeamLeaderDaySummaryVO2() {
        return (ViewObjectImpl) findViewObject("TeamLeaderDaySummaryVO2");
    }

    /**
     * Container's getter for TeamLeaderDaySummaryVL2.
     * @return TeamLeaderDaySummaryVL2
     */
    public ViewLinkImpl getTeamLeaderDaySummaryVL2() {
        return (ViewLinkImpl) findViewLink("TeamLeaderDaySummaryVL2");
    }

    /**
     * Container's getter for TeamLeaderPriorityVO1.
     * @return TeamLeaderPriorityVO1
     */
    public ViewObjectImpl getTeamLeaderPriorityVO1() {
        return (ViewObjectImpl) findViewObject("TeamLeaderPriorityVO1");
    }

    /**
     * Container's getter for TeamLeaderPriorityVL1.
     * @return TeamLeaderPriorityVL1
     */
    public ViewLinkImpl getTeamLeaderPriorityVL1() {
        return (ViewLinkImpl) findViewLink("TeamLeaderPriorityVL1");
    }

    /**
     * Container's getter for TeamLeaderNeedCallVO1.
     * @return TeamLeaderNeedCallVO1
     */
    public ViewObjectImpl getTeamLeaderNeedCallVO1() {
        return (ViewObjectImpl) findViewObject("TeamLeaderNeedCallVO1");
    }

    /**
     * Container's getter for TeamLeaderNeedCallVL1.
     * @return TeamLeaderNeedCallVL1
     */
    public ViewLinkImpl getTeamLeaderNeedCallVL1() {
        return (ViewLinkImpl) findViewLink("TeamLeaderNeedCallVL1");
    }


    /**
     * Container's getter for BulkSMSAddressVO1.
     * @return BulkSMSAddressVO1
     */
    public ViewObjectImpl getBulkSMSAddressVO1() {
        return (ViewObjectImpl) findViewObject("BulkSMSAddressVO1");
    }

    /**
     * Container's getter for PostponeDurationVO1.
     * @return PostponeDurationVO1
     */
    public PostponeDurationVOImpl getPostponeDurationVO1() {
        return (PostponeDurationVOImpl) findViewObject("PostponeDurationVO1");
    }


    /**
     * Container's getter for ContractDeliveryScheduleVO2.
     * @return ContractDeliveryScheduleVO2
     */
    public ViewObjectImpl getContractDeliveryScheduleVO2() {
        return (ViewObjectImpl) findViewObject("ContractDeliveryScheduleVO2");
    }

    /**
     * Container's getter for AreaContractProductContDelivVL1.
     * @return AreaContractProductContDelivVL1
     */
    public ViewLinkImpl getAreaContractProductContDelivVL1() {
        return (ViewLinkImpl) findViewLink("AreaContractProductContDelivVL1");
    }

    /**
     * Container's getter for ProductContractDeliveryVO2.
     * @return ProductContractDeliveryVO2
     */
    public ViewObjectImpl getProductContractDeliveryVO2() {
        return (ViewObjectImpl) findViewObject("ProductContractDeliveryVO2");
    }

    /**
     * Container's getter for ProductContractDelivContractDelScheduVL2.
     * @return ProductContractDelivContractDelScheduVL2
     */
    public ViewLinkImpl getProductContractDelivContractDelScheduVL2() {
        return (ViewLinkImpl) findViewLink("ProductContractDelivContractDelScheduVL2");
    }

    /**
     * Container's getter for AssignmentVO1.
     * @return AssignmentVO1
     */
    public ViewObjectImpl getAssignmentVO1() {
        return (ViewObjectImpl) findViewObject("AssignmentVO1");
    }

    /**
     * Container's getter for AssignmentProductContDeliveryVL1.
     * @return AssignmentProductContDeliveryVL1
     */
    public ViewLinkImpl getAssignmentProductContDeliveryVL1() {
        return (ViewLinkImpl) findViewLink("AssignmentProductContDeliveryVL1");
    }


    /**
     * Container's getter for ContractStatusVO1.
     * @return ContractStatusVO1
     */
    public ViewObjectImpl getContractStatusVO1() {
        return (ViewObjectImpl) findViewObject("ContractStatusVO1");
    }

    /**
     * Container's getter for AreaContractStatusVL1.
     * @return AreaContractStatusVL1
     */
    public ViewLinkImpl getAreaContractStatusVL1() {
        return (ViewLinkImpl) findViewLink("AreaContractStatusVL1");
    }

    /**
     * Container's getter for AgentAreasSummaryVO1.
     * @return AgentAreasSummaryVO1
     */
    public ViewObjectImpl getAgentAreasSummaryVO1() {
        return (ViewObjectImpl) findViewObject("AgentAreasSummaryVO1");
    }

    /**
     * Container's getter for AgentAreaSummaryVL1.
     * @return AgentAreaSummaryVL1
     */
    public ViewLinkImpl getAgentAreaSummaryVL1() {
        return (ViewLinkImpl) findViewLink("AgentAreaSummaryVL1");
    }

    /**
     * Container's getter for TeamLeaderDaySummaryVO1.
     * @return TeamLeaderDaySummaryVO1
     */
    public ViewObjectImpl getTeamLeaderDaySummaryVO1() {
        return (ViewObjectImpl) findViewObject("TeamLeaderDaySummaryVO1");
    }

    /**
     * Container's getter for TeamLeaderDaySummaryVL1.
     * @return TeamLeaderDaySummaryVL1
     */
    public ViewLinkImpl getTeamLeaderDaySummaryVL1() {
        return (ViewLinkImpl) findViewLink("TeamLeaderDaySummaryVL1");
    }

    /**
     * Container's getter for TeamLeaderPriorityVO2.
     * @return TeamLeaderPriorityVO2
     */
    public ViewObjectImpl getTeamLeaderPriorityVO2() {
        return (ViewObjectImpl) findViewObject("TeamLeaderPriorityVO2");
    }

    /**
     * Container's getter for TeamLeaderPriorityVL2.
     * @return TeamLeaderPriorityVL2
     */
    public ViewLinkImpl getTeamLeaderPriorityVL2() {
        return (ViewLinkImpl) findViewLink("TeamLeaderPriorityVL2");
    }

    /**
     * Container's getter for SupervisorAreaSummaryVO1.
     * @return SupervisorAreaSummaryVO1
     */
    public ViewObjectImpl getSupervisorAreaSummaryVO1() {
        return (ViewObjectImpl) findViewObject("SupervisorAreaSummaryVO1");
    }

    /**
     * Container's getter for SupervisorAreaSummaryVL1.
     * @return SupervisorAreaSummaryVL1
     */
    public ViewLinkImpl getSupervisorAreaSummaryVL1() {
        return (ViewLinkImpl) findViewLink("SupervisorAreaSummaryVL1");
    }

    /**
     * Container's getter for AssignmentSummaryVO1.
     * @return AssignmentSummaryVO1
     */
    public ViewObjectImpl getAssignmentSummaryVO1() {
        return (ViewObjectImpl) findViewObject("AssignmentSummaryVO1");
    }

    /**
     * Container's getter for AssignmentSummaryVL1.
     * @return AssignmentSummaryVL1
     */
    public ViewLinkImpl getAssignmentSummaryVL1() {
        return (ViewLinkImpl) findViewLink("AssignmentSummaryVL1");
    }


    /**
     * Container's getter for AssignedDriversSparesVO1.
     * @return AssignedDriversSparesVO1
     */
    public ViewObjectImpl getAssignedDriversSparesVO1() {
        return (ViewObjectImpl) findViewObject("AssignedDriversSparesVO1");
    }

    /**
     * Container's getter for AssignedDriversAreasVO3.
     * @return AssignedDriversAreasVO3
     */
    public ViewObjectImpl getAssignedDriversAreasVO3() {
        return (ViewObjectImpl) findViewObject("AssignedDriversAreasVO3");
    }

    /**
     * Container's getter for AssignedDriversSparesVO2.
     * @return AssignedDriversSparesVO2
     */
    public ViewObjectImpl getAssignedDriversSparesVO2() {
        return (ViewObjectImpl) findViewObject("AssignedDriversSparesVO2");
    }

    /**
     * Container's getter for AreaSparesVL1.
     * @return AreaSparesVL1
     */
    public ViewLinkImpl getAreaSparesVL1() {
        return (ViewLinkImpl) findViewLink("AreaSparesVL1");
    }

    /**
     * Container's getter for AssignedDriversSparesVO3.
     * @return AssignedDriversSparesVO3
     */
    public ViewObjectImpl getAssignedDriversSparesVO3() {
        return (ViewObjectImpl) findViewObject("AssignedDriversSparesVO3");
    }

    /**
     * Container's getter for AreaSparesVL2.
     * @return AreaSparesVL2
     */
    public ViewLinkImpl getAreaSparesVL2() {
        return (ViewLinkImpl) findViewLink("AreaSparesVL2");
    }

    /**
     * Container's getter for PromosLookupVO1.
     * @return PromosLookupVO1
     */
    public PromosLookupVOImpl getPromosLookupVO1() {
        return (PromosLookupVOImpl) findViewObject("PromosLookupVO1");
    }


    /**
     * Container's getter for TeamLeaderTotalsVO1.
     * @return TeamLeaderTotalsVO1
     */
    public ViewObjectImpl getTeamLeaderTotalsVO1() {
        return (ViewObjectImpl) findViewObject("TeamLeaderTotalsVO1");
    }

    /**
     * Container's getter for TeamLeaderAgentTotalsVL1.
     * @return TeamLeaderAgentTotalsVL1
     */
    public ViewLinkImpl getTeamLeaderAgentTotalsVL1() {
        return (ViewLinkImpl) findViewLink("TeamLeaderAgentTotalsVL1");
    }

    /**
     * Container's getter for TeamLeaderAgentSummaryVO1.
     * @return TeamLeaderAgentSummaryVO1
     */
    public ViewObjectImpl getTeamLeaderAgentSummaryVO1() {
        return (ViewObjectImpl) findViewObject("TeamLeaderAgentSummaryVO1");
    }

    /**
     * Container's getter for AgentSummaryDetailsVL1.
     * @return AgentSummaryDetailsVL1
     */
    public ViewLinkImpl getAgentSummaryDetailsVL1() {
        return (ViewLinkImpl) findViewLink("AgentSummaryDetailsVL1");
    }

    /**
     * Container's getter for AssignmentVO2.
     * @return AssignmentVO2
     */
    public ViewObjectImpl getAssignmentVO2() {
        return (ViewObjectImpl) findViewObject("AssignmentVO2");
    }

    /**
     * Container's getter for AreaContractAssignmentVL1.
     * @return AreaContractAssignmentVL1
     */
    public ViewLinkImpl getAreaContractAssignmentVL1() {
        return (ViewLinkImpl) findViewLink("AreaContractAssignmentVL1");
    }

    /**
     * Container's getter for ProductContractDeliveryDetVO1.
     * @return ProductContractDeliveryDetVO1
     */
    public ViewObjectImpl getProductContractDeliveryDetVO1() {
        return (ViewObjectImpl) findViewObject("ProductContractDeliveryDetVO1");
    }

    /**
     * Container's getter for AssignmentProductContDelDetVL1.
     * @return AssignmentProductContDelDetVL1
     */
    public ViewLinkImpl getAssignmentProductContDelDetVL1() {
        return (ViewLinkImpl) findViewLink("AssignmentProductContDelDetVL1");
    }

    /**
     * Container's getter for ContractDataVO1.
     * @return ContractDataVO1
     */
    public ViewObjectImpl getContractDataVO1() {
        return (ViewObjectImpl) findViewObject("ContractDataVO1");
    }

    /**
     * Container's getter for CollectionDetailsVO1.
     * @return CollectionDetailsVO1
     */
    public ViewObjectImpl getCollectionDetailsVO1() {
        return (ViewObjectImpl) findViewObject("CollectionDetailsVO1");
    }

    /**
     * Container's getter for CollectionDetailsVL1.
     * @return CollectionDetailsVL1
     */
    public ViewLinkImpl getCollectionDetailsVL1() {
        return (ViewLinkImpl) findViewLink("CollectionDetailsVL1");
    }


    /**
     * Container's getter for MobileAuditVO2.
     * @return MobileAuditVO2
     */
    public ViewObjectImpl getMobileAuditVO2() {
        return (ViewObjectImpl) findViewObject("MobileAuditVO2");
    }

    /**
     * Container's getter for MobileAuditVL2.
     * @return MobileAuditVL2
     */
    public ViewLinkImpl getMobileAuditVL2() {
        return (ViewLinkImpl) findViewLink("MobileAuditVL2");
    }

    /**
     * Container's getter for ContractResultVO1.
     * @return ContractResultVO1
     */
    public ViewObjectImpl getContractResultVO1() {
        return (ViewObjectImpl) findViewObject("ContractResultVO1");
    }

    /**
     * Container's getter for ContractDetailsVL1.
     * @return ContractDetailsVL1
     */
    public ViewLinkImpl getContractDetailsVL1() {
        return (ViewLinkImpl) findViewLink("ContractDetailsVL1");
    }

    /**
     * Container's getter for ProductTreatsPriceVO3.
     * @return ProductTreatsPriceVO3
     */
    public ProductTreatsPriceVOImpl getProductTreatsPriceVO3() {
        return (ProductTreatsPriceVOImpl) findViewObject("ProductTreatsPriceVO3");
    }

    /**
     * Container's getter for ProductRentPriceVO1.
     * @return ProductRentPriceVO1
     */
    public ViewObjectImpl getProductRentPriceVO1() {
        return (ViewObjectImpl) findViewObject("ProductRentPriceVO1");
    }

    /**
     * Container's getter for TreatmentTypesROV1.
     * @return TreatmentTypesROV1
     */
    public ViewObjectImpl getTreatmentTypesROV1() {
        return (ViewObjectImpl) findViewObject("TreatmentTypesROV1");
    }


    /**
     * Container's getter for DailyWorkVO2.
     * @return DailyWorkVO2
     */
    public ViewObjectImpl getDailyWorkVO2() {
        return (ViewObjectImpl) findViewObject("DailyWorkVO2");
    }

    /**
     * Container's getter for SupervisorAssignedStreetsVL1.
     * @return SupervisorAssignedStreetsVL1
     */
    public ViewLinkImpl getSupervisorAssignedStreetsVL1() {
        return (ViewLinkImpl) findViewLink("SupervisorAssignedStreetsVL1");
    }


    /**
     * Container's getter for SupervisorAreaMasterVO2.
     * @return SupervisorAreaMasterVO2
     */
    public ViewObjectImpl getSupervisorAreaMasterVO2() {
        return (ViewObjectImpl) findViewObject("SupervisorAreaMasterVO2");
    }

    /**
     * Container's getter for SupervisorAreaMasterVL2.
     * @return SupervisorAreaMasterVL2
     */
    public ViewLinkImpl getSupervisorAreaMasterVL2() {
        return (ViewLinkImpl) findViewLink("SupervisorAreaMasterVL2");
    }

    /**
     * Container's getter for SupervisorAreasDetailsVO1.
     * @return SupervisorAreasDetailsVO1
     */
    public ViewObjectImpl getSupervisorAreasDetailsVO1() {
        return (ViewObjectImpl) findViewObject("SupervisorAreasDetailsVO1");
    }

    /**
     * Container's getter for SupervisorMasterDetailsVL1.
     * @return SupervisorMasterDetailsVL1
     */
    public ViewLinkImpl getSupervisorMasterDetailsVL1() {
        return (ViewLinkImpl) findViewLink("SupervisorMasterDetailsVL1");
    }

    /**
     * Container's getter for AssignedDriversAreasVO4.
     * @return AssignedDriversAreasVO4
     */
    public ViewObjectImpl getAssignedDriversAreasVO4() {
        return (ViewObjectImpl) findViewObject("AssignedDriversAreasVO4");
    }

    /**
     * Container's getter for SupervisorDetailAssignedDriverVL1.
     * @return SupervisorDetailAssignedDriverVL1
     */
    public ViewLinkImpl getSupervisorDetailAssignedDriverVL1() {
        return (ViewLinkImpl) findViewLink("SupervisorDetailAssignedDriverVL1");
    }

    /**
     * Container's getter for AssignedDriversSparesVO4.
     * @return AssignedDriversSparesVO4
     */
    public ViewObjectImpl getAssignedDriversSparesVO4() {
        return (ViewObjectImpl) findViewObject("AssignedDriversSparesVO4");
    }

    /**
     * Container's getter for AreaSparesVL3.
     * @return AreaSparesVL3
     */
    public ViewLinkImpl getAreaSparesVL3() {
        return (ViewLinkImpl) findViewLink("AreaSparesVL3");
    }

    /**
     * Container's getter for DriversStreetVO2.
     * @return DriversStreetVO2
     */
    public ViewObjectImpl getDriversStreetVO2() {
        return (ViewObjectImpl) findViewObject("DriversStreetVO2");
    }

    /**
     * Container's getter for SupervisorDetailsAssignedStreetVL1.
     * @return SupervisorDetailsAssignedStreetVL1
     */
    public ViewLinkImpl getSupervisorDetailsAssignedStreetVL1() {
        return (ViewLinkImpl) findViewLink("SupervisorDetailsAssignedStreetVL1");
    }

    /**
     * Container's getter for NDriverVO1.
     * @return NDriverVO1
     */
    public ViewObjectImpl getNDriverVO1() {
        return (ViewObjectImpl) findViewObject("NDriverVO1");
    }

    /**
     * Container's getter for ProductsAndPackagesROV1.
     * @return ProductsAndPackagesROV1
     */
    public ViewObjectImpl getProductsAndPackagesROV1() {
        return (ViewObjectImpl) findViewObject("ProductsAndPackagesROV1");
    }

    /**
     * Container's getter for ArchiveDeliveryVO1.
     * @return ArchiveDeliveryVO1
     */
    public ViewObjectImpl getArchiveDeliveryVO1() {
        return (ViewObjectImpl) findViewObject("ArchiveDeliveryVO1");
    }

    /**
     * Container's getter for ArchiveAssVL1.
     * @return ArchiveAssVL1
     */
    public ViewLinkImpl getArchiveAssVL1() {
        return (ViewLinkImpl) findViewLink("ArchiveAssVL1");
    }

    /**
     * Container's getter for ArchiveDeliveryDetVO1.
     * @return ArchiveDeliveryDetVO1
     */
    public ViewObjectImpl getArchiveDeliveryDetVO1() {
        return (ViewObjectImpl) findViewObject("ArchiveDeliveryDetVO1");
    }

    /**
     * Container's getter for ArchiveDelDetVL1.
     * @return ArchiveDelDetVL1
     */
    public ViewLinkImpl getArchiveDelDetVL1() {
        return (ViewLinkImpl) findViewLink("ArchiveDelDetVL1");
    }

    /**
     * Container's getter for ArchiveContractResVO1.
     * @return ArchiveContractResVO1
     */
    public ViewObjectImpl getArchiveContractResVO1() {
        return (ViewObjectImpl) findViewObject("ArchiveContractResVO1");
    }

    /**
     * Container's getter for ArchiveContractActionVL1.
     * @return ArchiveContractActionVL1
     */
    public ViewLinkImpl getArchiveContractActionVL1() {
        return (ViewLinkImpl) findViewLink("ArchiveContractActionVL1");
    }

    /**
     * Container's getter for ArchiveCollectionVO1.
     * @return ArchiveCollectionVO1
     */
    public ViewObjectImpl getArchiveCollectionVO1() {
        return (ViewObjectImpl) findViewObject("ArchiveCollectionVO1");
    }

    /**
     * Container's getter for ArchiveCollectionVL1.
     * @return ArchiveCollectionVL1
     */
    public ViewLinkImpl getArchiveCollectionVL1() {
        return (ViewLinkImpl) findViewLink("ArchiveCollectionVL1");
    }

    /**
     * Container's getter for ArchiveDeliveryVO2.
     * @return ArchiveDeliveryVO2
     */
    public ViewObjectImpl getArchiveDeliveryVO2() {
        return (ViewObjectImpl) findViewObject("ArchiveDeliveryVO2");
    }

    /**
     * Container's getter for ArchiveMobileAuditVO1.
     * @return ArchiveMobileAuditVO1
     */
    public ViewObjectImpl getArchiveMobileAuditVO1() {
        return (ViewObjectImpl) findViewObject("ArchiveMobileAuditVO1");
    }

    /**
     * Container's getter for ArchiveMobileTransVL1.
     * @return ArchiveMobileTransVL1
     */
    public ViewLinkImpl getArchiveMobileTransVL1() {
        return (ViewLinkImpl) findViewLink("ArchiveMobileTransVL1");
    }

    /**
     * Container's getter for ArchiveMobileAuditVO2.
     * @return ArchiveMobileAuditVO2
     */
    public ViewObjectImpl getArchiveMobileAuditVO2() {
        return (ViewObjectImpl) findViewObject("ArchiveMobileAuditVO2");
    }

    /**
     * Container's getter for ArchiveMobileTransVL2.
     * @return ArchiveMobileTransVL2
     */
    public ViewLinkImpl getArchiveMobileTransVL2() {
        return (ViewLinkImpl) findViewLink("ArchiveMobileTransVL2");
    }

    /**
     * Container's getter for SelectedDayVO1.
     * @return SelectedDayVO1
     */
    public ViewObjectImpl getSelectedDayVO1() {
        return (ViewObjectImpl) findViewObject("SelectedDayVO1");
    }

    /**
     * Container's getter for SMSTempVO1.
     * @return SMSTempVO1
     */
    public ViewObjectImpl getSMSTempVO1() {
        return (ViewObjectImpl) findViewObject("SMSTempVO1");
    }

    /**
     * Container's getter for AdhocContractsVO1.
     * @return AdhocContractsVO1
     */
    public ViewObjectImpl getAdhocContractsVO1() {
        return (ViewObjectImpl) findViewObject("AdhocContractsVO1");
    }

    /**
     * Container's getter for AreaContractVO1.
     * @return AreaContractVO1
     */
    public ViewObjectImpl getAreaContractVO1() {
        return (ViewObjectImpl) findViewObject("AreaContractVO1");
    }


    /**
     * Container's getter for AreaContractInformationVO2.
     * @return AreaContractInformationVO2
     */
    public AreaContractInformationVOImpl getAreaContractInformationVO2() {
        return (AreaContractInformationVOImpl) findViewObject("AreaContractInformationVO2");
    }

    /**
     * Container's getter for AreaContractContInfoVL1.
     * @return AreaContractContInfoVL1
     */
    public ViewLinkImpl getAreaContractContInfoVL1() {
        return (ViewLinkImpl) findViewLink("AreaContractContInfoVL1");
    }


    /**
     * Container's getter for ContractDataVO2.
     * @return ContractDataVO2
     */
    public ViewObjectImpl getContractDataVO2() {
        return (ViewObjectImpl) findViewObject("ContractDataVO2");
    }

    /**
     * Container's getter for AdhocContractVL1.
     * @return AdhocContractVL1
     */
    public ViewLinkImpl getAdhocContractVL1() {
        return (ViewLinkImpl) findViewLink("AdhocContractVL1");
    }

    /**
     * Container's getter for AssignmentVO3.
     * @return AssignmentVO3
     */
    public ViewObjectImpl getAssignmentVO3() {
        return (ViewObjectImpl) findViewObject("AssignmentVO3");
    }

    /**
     * Container's getter for AssignmentAdhocVL1.
     * @return AssignmentAdhocVL1
     */
    public ViewLinkImpl getAssignmentAdhocVL1() {
        return (ViewLinkImpl) findViewLink("AssignmentAdhocVL1");
    }

    /**
     * Container's getter for CollectionDetailsVO2.
     * @return CollectionDetailsVO2
     */
    public ViewObjectImpl getCollectionDetailsVO2() {
        return (ViewObjectImpl) findViewObject("CollectionDetailsVO2");
    }

    /**
     * Container's getter for CollectionDetailsVL2.
     * @return CollectionDetailsVL2
     */
    public ViewLinkImpl getCollectionDetailsVL2() {
        return (ViewLinkImpl) findViewLink("CollectionDetailsVL2");
    }

    /**
     * Container's getter for AssignmentVO4.
     * @return AssignmentVO4
     */
    public ViewObjectImpl getAssignmentVO4() {
        return (ViewObjectImpl) findViewObject("AssignmentVO4");
    }

    /**
     * Container's getter for ContractResultVO2.
     * @return ContractResultVO2
     */
    public ViewObjectImpl getContractResultVO2() {
        return (ViewObjectImpl) findViewObject("ContractResultVO2");
    }

    /**
     * Container's getter for ContractDetailsVL2.
     * @return ContractDetailsVL2
     */
    public ViewLinkImpl getContractDetailsVL2() {
        return (ViewLinkImpl) findViewLink("ContractDetailsVL2");
    }

    /**
     * Container's getter for ContractResultVO3.
     * @return ContractResultVO3
     */
    public ViewObjectImpl getContractResultVO3() {
        return (ViewObjectImpl) findViewObject("ContractResultVO3");
    }

    /**
     * Container's getter for ContractDetailsVL3.
     * @return ContractDetailsVL3
     */
    public ViewLinkImpl getContractDetailsVL3() {
        return (ViewLinkImpl) findViewLink("ContractDetailsVL3");
    }

    /**
     * Container's getter for ProductContractDeliveryVO1.
     * @return ProductContractDeliveryVO1
     */
    public ProductContractDeliveryVOImpl getProductContractDeliveryVO1() {
        return (ProductContractDeliveryVOImpl) findViewObject("ProductContractDeliveryVO1");
    }

    /**
     * Container's getter for AssignmentVO5.
     * @return AssignmentVO5
     */
    public ViewObjectImpl getAssignmentVO5() {
        return (ViewObjectImpl) findViewObject("AssignmentVO5");
    }

    /**
     * Container's getter for ProductContDelivAssignmentVL1.
     * @return ProductContDelivAssignmentVL1
     */
    public ViewLinkImpl getProductContDelivAssignmentVL1() {
        return (ViewLinkImpl) findViewLink("ProductContDelivAssignmentVL1");
    }

    /**
     * Container's getter for ProductContractDeliveryVO3.
     * @return ProductContractDeliveryVO3
     */
    public ProductContractDeliveryVOImpl getProductContractDeliveryVO3() {
        return (ProductContractDeliveryVOImpl) findViewObject("ProductContractDeliveryVO3");
    }

    /**
     * Container's getter for AssignmentVO6.
     * @return AssignmentVO6
     */
    public ViewObjectImpl getAssignmentVO6() {
        return (ViewObjectImpl) findViewObject("AssignmentVO6");
    }

    /**
     * Container's getter for ProductContDelivAssignmentVL2.
     * @return ProductContDelivAssignmentVL2
     */
    public ViewLinkImpl getProductContDelivAssignmentVL2() {
        return (ViewLinkImpl) findViewLink("ProductContDelivAssignmentVL2");
    }

    /**
     * Container's getter for ContractDeliveryScheduleVO1.
     * @return ContractDeliveryScheduleVO1
     */
    public ViewObjectImpl getContractDeliveryScheduleVO1() {
        return (ViewObjectImpl) findViewObject("ContractDeliveryScheduleVO1");
    }

    /**
     * Container's getter for ProductContractDeliveryVO4.
     * @return ProductContractDeliveryVO4
     */
    public ProductContractDeliveryVOImpl getProductContractDeliveryVO4() {
        return (ProductContractDeliveryVOImpl) findViewObject("ProductContractDeliveryVO4");
    }

    /**
     * Container's getter for ProductContractDelivContractDelScheduVL1.
     * @return ProductContractDelivContractDelScheduVL1
     */
    public ViewLinkImpl getProductContractDelivContractDelScheduVL1() {
        return (ViewLinkImpl) findViewLink("ProductContractDelivContractDelScheduVL1");
    }

    /**
     * Container's getter for ProductContractDeliveryDetVO2.
     * @return ProductContractDeliveryDetVO2
     */
    public ViewObjectImpl getProductContractDeliveryDetVO2() {
        return (ViewObjectImpl) findViewObject("ProductContractDeliveryDetVO2");
    }

    /**
     * Container's getter for AssignmentProductContDelDetVL2.
     * @return AssignmentProductContDelDetVL2
     */
    public ViewLinkImpl getAssignmentProductContDelDetVL2() {
        return (ViewLinkImpl) findViewLink("AssignmentProductContDelDetVL2");
    }

    /**
     * Container's getter for MobileAuditVO1.
     * @return MobileAuditVO1
     */
    public ViewObjectImpl getMobileAuditVO1() {
        return (ViewObjectImpl) findViewObject("MobileAuditVO1");
    }

    /**
     * Container's getter for MobileAuditVL1.
     * @return MobileAuditVL1
     */
    public ViewLinkImpl getMobileAuditVL1() {
        return (ViewLinkImpl) findViewLink("MobileAuditVL1");
    }


    /**
     * Container's getter for OpenTicketVO2.
     * @return OpenTicketVO2
     */
    public ViewObjectImpl getOpenTicketVO2() {
        return (ViewObjectImpl) findViewObject("OpenTicketVO2");
    }

    /**
     * Container's getter for AdhocTicketsVL2.
     * @return AdhocTicketsVL2
     */
    public ViewLinkImpl getAdhocTicketsVL2() {
        return (ViewLinkImpl) findViewLink("AdhocTicketsVL2");
    }

    /**
     * Container's getter for ArchiveDeliveryVO3.
     * @return ArchiveDeliveryVO3
     */
    public ViewObjectImpl getArchiveDeliveryVO3() {
        return (ViewObjectImpl) findViewObject("ArchiveDeliveryVO3");
    }

    /**
     * Container's getter for AdhocArchiveDeliveryVL1.
     * @return AdhocArchiveDeliveryVL1
     */
    public ViewLinkImpl getAdhocArchiveDeliveryVL1() {
        return (ViewLinkImpl) findViewLink("AdhocArchiveDeliveryVL1");
    }

    /**
     * Container's getter for ArchiveCollectionVO2.
     * @return ArchiveCollectionVO2
     */
    public ViewObjectImpl getArchiveCollectionVO2() {
        return (ViewObjectImpl) findViewObject("ArchiveCollectionVO2");
    }

    /**
     * Container's getter for ArchiveCollectionVL2.
     * @return ArchiveCollectionVL2
     */
    public ViewLinkImpl getArchiveCollectionVL2() {
        return (ViewLinkImpl) findViewLink("ArchiveCollectionVL2");
    }

    /**
     * Container's getter for ArchiveContractResVO2.
     * @return ArchiveContractResVO2
     */
    public ViewObjectImpl getArchiveContractResVO2() {
        return (ViewObjectImpl) findViewObject("ArchiveContractResVO2");
    }

    /**
     * Container's getter for ArchiveContractActionVL2.
     * @return ArchiveContractActionVL2
     */
    public ViewLinkImpl getArchiveContractActionVL2() {
        return (ViewLinkImpl) findViewLink("ArchiveContractActionVL2");
    }

    /**
     * Container's getter for ArchiveDeliveryVO4.
     * @return ArchiveDeliveryVO4
     */
    public ViewObjectImpl getArchiveDeliveryVO4() {
        return (ViewObjectImpl) findViewObject("ArchiveDeliveryVO4");
    }

    /**
     * Container's getter for ArchiveMobileAuditVO3.
     * @return ArchiveMobileAuditVO3
     */
    public ViewObjectImpl getArchiveMobileAuditVO3() {
        return (ViewObjectImpl) findViewObject("ArchiveMobileAuditVO3");
    }

    /**
     * Container's getter for ArchiveMobileTransVL3.
     * @return ArchiveMobileTransVL3
     */
    public ViewLinkImpl getArchiveMobileTransVL3() {
        return (ViewLinkImpl) findViewLink("ArchiveMobileTransVL3");
    }

    /**
     * Container's getter for ArchiveMobileAuditVO4.
     * @return ArchiveMobileAuditVO4
     */
    public ViewObjectImpl getArchiveMobileAuditVO4() {
        return (ViewObjectImpl) findViewObject("ArchiveMobileAuditVO4");
    }

    /**
     * Container's getter for ArchiveMobileTransVL4.
     * @return ArchiveMobileTransVL4
     */
    public ViewLinkImpl getArchiveMobileTransVL4() {
        return (ViewLinkImpl) findViewLink("ArchiveMobileTransVL4");
    }

    /**
     * Container's getter for ArchiveDeliveryDetVO2.
     * @return ArchiveDeliveryDetVO2
     */
    public ViewObjectImpl getArchiveDeliveryDetVO2() {
        return (ViewObjectImpl) findViewObject("ArchiveDeliveryDetVO2");
    }

    /**
     * Container's getter for ArchiveDelDetVL2.
     * @return ArchiveDelDetVL2
     */
    public ViewLinkImpl getArchiveDelDetVL2() {
        return (ViewLinkImpl) findViewLink("ArchiveDelDetVL2");
    }


    /**
     * Container's getter for ProductContractVO1.
     * @return ProductContractVO1
     */
    public ProductContractVOImpl getProductContractVO1() {
        return (ProductContractVOImpl) findViewObject("ProductContractVO1");
    }

    /**
     * Container's getter for AdhocProductContractVL1.
     * @return AdhocProductContractVL1
     */
    public ViewLinkImpl getAdhocProductContractVL1() {
        return (ViewLinkImpl) findViewLink("AdhocProductContractVL1");
    }

    /**
     * Container's getter for PromosDeliveryVO1.
     * @return PromosDeliveryVO1
     */
    public PromosDeliveryVOImpl getPromosDeliveryVO1() {
        return (PromosDeliveryVOImpl) findViewObject("PromosDeliveryVO1");
    }

    /**
     * Container's getter for AdhocPromosVL1.
     * @return AdhocPromosVL1
     */
    public ViewLinkImpl getAdhocPromosVL1() {
        return (ViewLinkImpl) findViewLink("AdhocPromosVL1");
    }

    /**
     * Container's getter for ProductContractVO2.
     * @return ProductContractVO2
     */
    public ProductContractVOImpl getProductContractVO2() {
        return (ProductContractVOImpl) findViewObject("ProductContractVO2");
    }

    /**
     * Container's getter for BulkSMSVO1.
     * @return BulkSMSVO1
     */
    public ViewObjectImpl getBulkSMSVO1() {
        return (ViewObjectImpl) findViewObject("BulkSMSVO1");
    }

    /**
     * Container's getter for WeekDaysVO1.
     * @return WeekDaysVO1
     */
    public WeekDaysVOImpl getWeekDaysVO1() {
        return (WeekDaysVOImpl) findViewObject("WeekDaysVO1");
    }

    /**
     * Container's getter for InvoiceScheduleVO1.
     * @return InvoiceScheduleVO1
     */
    public InvoiceScheduleVOImpl getInvoiceScheduleVO1() {
        return (InvoiceScheduleVOImpl) findViewObject("InvoiceScheduleVO1");
    }

    /**
     * Container's getter for InvoiceScheduleVL1.
     * @return InvoiceScheduleVL1
     */
    public ViewLinkImpl getInvoiceScheduleVL1() {
        return (ViewLinkImpl) findViewLink("InvoiceScheduleVL1");
    }

    /**
     * Container's getter for AccountingAgentVO1.
     * @return AccountingAgentVO1
     */
    public ViewObjectImpl getAccountingAgentVO1() {
        return (ViewObjectImpl) findViewObject("AccountingAgentVO1");
    }

    /**
     * Container's getter for InvoiceScheduleAccountVO1.
     * @return InvoiceScheduleAccountVO1
     */
    public InvoiceScheduleAccountVOImpl getInvoiceScheduleAccountVO1() {
        return (InvoiceScheduleAccountVOImpl) findViewObject("InvoiceScheduleAccountVO1");
    }

    /**
     * Container's getter for ContractInvoiceSummaryVO1.
     * @return ContractInvoiceSummaryVO1
     */
    public ViewObjectImpl getContractInvoiceSummaryVO1() {
        return (ViewObjectImpl) findViewObject("ContractInvoiceSummaryVO1");
    }

    /**
     * Container's getter for InvoiceContractSummaryVL1.
     * @return InvoiceContractSummaryVL1
     */
    public ViewLinkImpl getInvoiceContractSummaryVL1() {
        return (ViewLinkImpl) findViewLink("InvoiceContractSummaryVL1");
    }

    /**
     * Container's getter for WeekDaysVO2.
     * @return WeekDaysVO2
     */
    public WeekDaysVOImpl getWeekDaysVO2() {
        return (WeekDaysVOImpl) findViewObject("WeekDaysVO2");
    }

    /**
     * Container's getter for InvoiceScheduleAccountVO2.
     * @return InvoiceScheduleAccountVO2
     */
    public InvoiceScheduleAccountVOImpl getInvoiceScheduleAccountVO2() {
        return (InvoiceScheduleAccountVOImpl) findViewObject("InvoiceScheduleAccountVO2");
    }

    /**
     * Container's getter for InvoiceAgentWorkVL1.
     * @return InvoiceAgentWorkVL1
     */
    public ViewLinkImpl getInvoiceAgentWorkVL1() {
        return (ViewLinkImpl) findViewLink("InvoiceAgentWorkVL1");
    }

    /**
     * Container's getter for ContractInvoiceSummaryVO2.
     * @return ContractInvoiceSummaryVO2
     */
    public ViewObjectImpl getContractInvoiceSummaryVO2() {
        return (ViewObjectImpl) findViewObject("ContractInvoiceSummaryVO2");
    }

    /**
     * Container's getter for InvoiceContractSummaryVL2.
     * @return InvoiceContractSummaryVL2
     */
    public ViewLinkImpl getInvoiceContractSummaryVL2() {
        return (ViewLinkImpl) findViewLink("InvoiceContractSummaryVL2");
    }

    /**
     * Container's getter for FilteredInvoicesVO1.
     * @return FilteredInvoicesVO1
     */
    public ViewObjectImpl getFilteredInvoicesVO1() {
        return (ViewObjectImpl) findViewObject("FilteredInvoicesVO1");
    }

    /**
     * Container's getter for FilteredInvoicesVL1.
     * @return FilteredInvoicesVL1
     */
    public ViewLinkImpl getFilteredInvoicesVL1() {
        return (ViewLinkImpl) findViewLink("FilteredInvoicesVL1");
    }

    /**
     * Container's getter for CollectionDriversVO2.
     * @return CollectionDriversVO2
     */
    public ViewObjectImpl getCollectionDriversVO2() {
        return (ViewObjectImpl) findViewObject("CollectionDriversVO2");
    }

    /**
     * Container's getter for CollectorsVO1.
     * @return CollectorsVO1
     */
    public ViewObjectImpl getCollectorsVO1() {
        return (ViewObjectImpl) findViewObject("CollectorsVO1");
    }

    /**
     * Container's getter for SpareVO2.
     * @return SpareVO2
     */
    public ViewObjectImpl getCollectionSpareVO2() {
        return (ViewObjectImpl) findViewObject("CollectionSpareVO2");
    }
}

