package OPERATIONPROJECT.model.BC.VO.Lookups;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 12 16:59:29 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductTreatsPriceVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProductTreatsPriceVOImpl() {
    }

    /**
     * Returns the variable value for ProductId.
     * @return variable value for ProductId
     */
    public String getProductId() {
        return (String) ensureVariableManager().getVariableValue("ProductId");
    }

    /**
     * Sets <code>value</code> for variable ProductId.
     * @param value value to bind as ProductId
     */
    public void setProductId(String value) {
        ensureVariableManager().setVariableValue("ProductId", value);
    }

    /**
     * Returns the variable value for Treatment_id.
     * @return variable value for Treatment_id
     */
    public Long getTreatment_id() {
        return (Long) ensureVariableManager().getVariableValue("Treatment_id");
    }

    /**
     * Sets <code>value</code> for variable Treatment_id.
     * @param value value to bind as Treatment_id
     */
    public void setTreatment_id(Long value) {
        ensureVariableManager().setVariableValue("Treatment_id", value);
    }
}

