package OPERATIONPROJECT.model.BC.VO.Lookups;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 12 16:58:44 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductTreatsPriceVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        DmsProductId,
        ProductName,
        TreatmentId,
        TreatmentName,
        SellingPrice;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DMSPRODUCTID = AttributesEnum.DmsProductId.index();
    public static final int PRODUCTNAME = AttributesEnum.ProductName.index();
    public static final int TREATMENTID = AttributesEnum.TreatmentId.index();
    public static final int TREATMENTNAME = AttributesEnum.TreatmentName.index();
    public static final int SELLINGPRICE = AttributesEnum.SellingPrice.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProductTreatsPriceVORowImpl() {
    }
}

