package OPERATIONPROJECT.model.BC.VO.Lookups;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 17 07:45:10 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PromosLookupVODefImpl extends ViewDefImpl {
    public PromosLookupVODefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public PromosLookupVODefImpl() {
    }
}

