package OPERATIONPROJECT.model.BC.VO.Lookups;

import OPERATIONPROJECT.model.BC.EO.PrmosLookupEOImpl;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 17 07:45:04 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PromosLookupVORowImpl extends ViewRowImpl {
    public static final int ENTITY_PRMOSLOOKUPEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ProductId,
        ProductName,
        SellingPrice;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PRODUCTID = AttributesEnum.ProductId.index();
    public static final int PRODUCTNAME = AttributesEnum.ProductName.index();
    public static final int SELLINGPRICE = AttributesEnum.SellingPrice.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PromosLookupVORowImpl() {
    }

    /**
     * Gets PrmosLookupEO entity object.
     * @return the PrmosLookupEO
     */
    public PrmosLookupEOImpl getPrmosLookupEO() {
        return (PrmosLookupEOImpl) getEntity(ENTITY_PRMOSLOOKUPEO);
    }

    /**
     * Gets the attribute value for PRODUCT_ID using the alias name ProductId.
     * @return the PRODUCT_ID
     */
    public String getProductId() {
        return (String) getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_ID using the alias name ProductId.
     * @param value value to set the PRODUCT_ID
     */
    public void setProductId(String value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for PRODUCT_NAME using the alias name ProductName.
     * @return the PRODUCT_NAME
     */
    public String getProductName() {
        return (String) getAttributeInternal(PRODUCTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_NAME using the alias name ProductName.
     * @param value value to set the PRODUCT_NAME
     */
    public void setProductName(String value) {
        setAttributeInternal(PRODUCTNAME, value);
    }

    /**
     * Gets the attribute value for SELLING_PRICE using the alias name SellingPrice.
     * @return the SELLING_PRICE
     */
    public Long getSellingPrice() {
        return (Long) getAttributeInternal(SELLINGPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for SELLING_PRICE using the alias name SellingPrice.
     * @param value value to set the SELLING_PRICE
     */
    public void setSellingPrice(Long value) {
        setAttributeInternal(SELLINGPRICE, value);
    }
}

