package OPERATIONPROJECT.model.BC.VO.Lookups;

import java.math.BigInteger;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 06 16:24:07 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StreetVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StreetVOImpl() {
    }
}

