package OPERATIONPROJECT.model.BC.VO.Lookups;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 21 23:13:59 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class YesOrNoSLVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public YesOrNoSLVImpl() {
    }
}

